### ISSUE TITLE
application.ini AccessLog.Layout parameter %O %r can't set a fixed width as other parameter %t%T or %i%I

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#111]
%r : First line of request
%O : Bytes sent, including headers, cannot be zero
if could set output width to them, access.log could looks pretty more. 

treefrog.log and app.log could set it as bellow:
FileLogger.Layout="%d %5P [%5t] %m%n"

and the log is:
2016-08-22 15:22:42 INFO  [ 2108] AppController
2016-08-22 15:22:45 INFO  [10276] AppController

**Comment by aoym** [comment]
>%r : First line of request
>%O : Bytes sent, including headers, cannot be zero
>if could set output width to them, access.log could looks pretty more.

It looks like good.
This is your idea or others?

**Comment by hks2002** [comment]
This is my idea. 
I tried to setting treefrog.log and app.log, access.log layout, and found access.log was different, i can't set it as treefrog.log and app.log with a prefixed width using '%5t'.

**Comment by aoym** [comment]
> if could set output width to them, access.log could looks pretty more.

Could you send a pull-request for this?

**Comment by hks2002** [comment]
Yes，I will do it.
