### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by proostas** [treefrogframework/treefrog-framework#113]
Good day, everyone!

Using: treefrog version 1.12.0 (r1112) built on Sep  3 2016 / Qt 5.5.1
I suspect next line in the controller to cause the error: 
        session().insert("id", session_q.value(0).toInt());

Sessions' backend is Redis. There are no errors in the logs of Redis.

What could possibly these errors mean? When this happens http server stops operating and only "treefrog -k abort && treefrog -d -e dev" helps. This happens absolutely unpredictably from time to time.

2017-01-01 03:14:04 WARN  [23148] QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread (:0 ) 
2017-01-01 03:14:04 WARN  [23142] QSocketNotifier: Invalid socket 18 and type 'Read', disabling... (:0 ) 
2017-01-01 03:14:05 ERROR [23142] Aborted at 1483226045 (unix time) try "date -d @1483226045" if you are using GNU date 
SIGSEGV (@0x0) received by PID 15691 (TID 23142) ; stack trace: 
PC: @     0x7fccf7934341  __GI_strlen 
    @     0x7fccf849d670  (unknown) 
    @     0x7fccf7934341  __GI_strlen 
    @     0x7fccf87e6efd  (unknown) 
    @     0x7fccf873c79e  (unknown) 
    @     0x7fccf873d578  (unknown) 
    @     0x7fccf89823a5  (unknown) 
    @     0x7fccf4419081  (unknown) 
    @     0x7fccf441959b  (unknown) 
    @     0x7fccf441970c  (unknown) 
    @     0x7fccf89824dc  (unknown) 
    @     0x7fccf92670ed  (unknown) 
    @     0x7fccf874facf  (unknown) 
    @     0x7fccf8495ce2  start_thread 
    @     0x7fccf79a4abd  __clone 
    @                0x0  (unknown) 
 
2017-01-01 03:14:05 ERROR [32589] tfserver error detected(1). [/usr/bin/tadpole] 
2017-01-01 03:14:05 ERROR [32589] Detected a server crashed. exitCode:11  exitStatus:1
2017-01-01 03:14:05 INFO  [23154] KVS database available. type:1

**Comment by proostas** [comment]
Tried to build 1.14.0 to test with it for the issue, but the build failed:

stas@jera:~/src/treefrog-framework-1.14.0/tools# make
cd tfmanager/ && ( test -e Makefile || /usr/bin/qmake /root/src/treefrog-framework-1.14.0/tools/tfmanager/tfmanager.pro -spec linux-g++ CONFIG+=x86_64 CONFIG+=release 'target.path="/usr/bin"' 'header.path="/usr/include/treefrog"' 'datadir="/usr/share/treefrog"' 'lib.path="/usr/lib"' -o Makefile ) && make -f Makefile 
make[1]: Entering directory `/root/src/treefrog-framework-1.14.0/tools/tfmanager'
g++ -c -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DTF_DLL -DTF_VERSION=\"1.14.0\" -DINSTALL_PATH=\"/usr/bin\" -DTF_NO_DEBUG -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/treefrog -I/usr/local/qt/5.5.1/include -I/usr/local/qt/5.5.1/include/QtNetwork -I/usr/local/qt/5.5.1/include/QtCore -I. -I/usr/local/qt/5.5.1/mkspecs/linux-g++ -o main.o main.cpp
In file included from main.cpp:16:0:
servermanager.h:51:33: error: ISO C++ forbids declaration of ‘T_DISABLE_COPY’ with no type [-fpermissive]
     T_DISABLE_COPY(ServerManager)
                                 ^
servermanager.h:51:33: error: expected ‘;’ at end of member declaration
servermanager.h:52:33: error: ISO C++ forbids declaration of ‘T_DISABLE_MOVE’ with no type [-fpermissive]
     T_DISABLE_MOVE(ServerManager)
                                 ^
servermanager.h:52:33: error: expected ‘;’ at end of member declaration
In file included from main.cpp:17:0:
systembusdaemon.h:35:35: error: ISO C++ forbids declaration of ‘T_DISABLE_COPY’ with no type [-fpermissive]
     T_DISABLE_COPY(SystemBusDaemon)
                                   ^
systembusdaemon.h:35:35: error: expected ‘;’ at end of member declaration
systembusdaemon.h:36:35: error: ISO C++ forbids declaration of ‘T_DISABLE_MOVE’ with no type [-fpermissive]
     T_DISABLE_MOVE(SystemBusDaemon)
                                   ^
systembusdaemon.h:36:35: error: expected ‘;’ at end of member declaration
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/root/src/treefrog-framework-1.14.0/tools/tfmanager'
make: *** [sub-tfmanager-make_first] Error 2

**Comment by proostas** [comment]
UPDATE: sorry, my fault: these errors are because I didn't run make install in src dir. Successfully compiled 1.14.0.

I will try debuging app with the new build and, if it fails, I am going to turn to storing session data in PostgreSQL since it now works fine. After all, Redis was a workaround for the PostgreSQL bug for me.

**Comment by treefrogframework** [comment]
Thanks.

**Comment by proostas** [comment]
After some observation, I reckon that these errors are connected with Redis itself and lack of RAM.
