### ISSUE TITLE
suggest composite primary keys support

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#116]
Does treefrogframework ORM have a plan to support comosite primary keys?
I suggest treefrogframework could achieve this, so that the default sqlobject/model class generated by tspawn tools could show the true all primary keys in method and properties. If a table have composite primary keys, the current function findByPrimaryKey(QVariant pk) is not fit the table, and if the person dones't known how the table define in database, he doesn't known all primary keys field.

**Comment by treefrogframework** [comment]
We discussed about this before.  #48
I think there are many disadvantages.

**Comment by treefrogframework** [comment]
Because of a lack of clear advantage, I have no plan that tspawn tool supports this feature.
