### ISSUE TITLE
muti fields orderby support in sqlormapper.h

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#117]
Wish treefrogframework could enchance the sqlormapper class. 
so that we could use mapper.orderBy(field1,Tf::AscendingOrder).orderBy(field2,Tf::AscendingOrder),
In most application, we need sort the table data more than one field.

**Comment by treefrogframework** [comment]
implemented d55812be85b65ef00a9de194fd95f8625fcc2421

**Comment by hks2002** [comment]
thanks
