### ISSUE TITLE
Add OTHER_FILES erb/html/otm files in views/_src/_src.pro

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#127]
Currently, in Qt creator, the views (erb/html/otm)files doesn't list in the project, so we need to go to these folders then open them. when coding, if we write controller and write views at the same time, change selected view files, it became so inconvenience.

**Comment by treefrogframework** [comment]
any idea?

**Comment by hks2002** [comment]
When create a view, add the its .erb or .html/.otm files to .pro
So we can see all views files list in the project tree of QtCreator.

**Comment by treefrogframework** [comment]
Implemented in 61973aa7f5ac8bd9b4ebc2596e778a646fbf1ef4 .
Try it.

**Comment by hks2002** [comment]
I tried it, it seems must after run make command, view files(erb/orm/html) then displays. It's still not very convenient. 
I think it is better if you could change it as bellow:
1. _src/src.pro add new line "include(../views.list)".
2. add a new "views.list" file directly under the views file folder, this file contains all controller related erb/otm/html files, when use tspawn command create/delete a new controller/action(views), add/delete it into this file(or regenerate this file) , you should be aware of that each file path is like this "../controller/action.erb", not "controller/action.erb".
Now all views erb/otm/html listed in the project tree, each controller with one folder, Nice.
![image](http://a1.qpic.cn/psb?/V14OTeoy25d9cz/Su0LPq91Cbfva18L*y9NvpM4Mk.jgq86SPOZRELqlv8!/b/dG4BAAAAAAAA&bo=HAOrAQAAAAADB5c!&rf=viewer_4)
![image](http://a2.qpic.cn/psb?/V14OTeoy25d9cz/fRoIiQ5xnn2OKzJOGkOiclm6pi1v3qQa11ur8n9tJkQ!/b/dGwBAAAAAAAA&bo=7ALTAQAAAAADBx4!&rf=viewer_4)

**Comment by treefrogframework** [comment]
Tell what is different.
View files can be generated not only automatically but also manually.

**Comment by hks2002** [comment]
First, i think we focus the erb/otm/html files in develop,rather than the cpp files. So,maybe we doesn't need to going to the cpp source folders. Let erb/otm/html not so deep in the tree node is better,that's we focus.
Second, through it can be edited/changed by manually, when use tspawn command batch created a lot of new erb/otm/html, it is a waste of time to add otm/html files to the list again by manually, or someone add new one but he forget add it to the list, So, automatic update is need, both after run tspawn and tmake.

**Comment by hks2002** [comment]
And, not very time, we run make after added view files, them are in developing, complete developing then run make, during this periods, we also need them listed in the Qt project tree.

**Comment by treefrogframework** [comment]
It's enough in 61973aa7f5ac8bd9b4ebc2596e778a646fbf1ef4, isn't it?

**Comment by hks2002** [comment]
as the description in views documents, run this command, when add new templates:
$cd views
$make qmake
new files will be add to the .pro
