### ISSUE TITLE
Crash when debugging WebSocketEndpoint application in QtCreator

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#140]
When I run application from TreeFrog Command Prompt (treefrogd -e dev) everything is OK,
but application crashes while debugging it in QtCreator.
The crash happens just after ChatEndpoint::onOpen() call.

![1](https://cloud.githubusercontent.com/assets/9396016/24957556/6138848e-1f8c-11e7-89fb-66532f1fcfa7.png)
![2](https://cloud.githubusercontent.com/assets/9396016/24957559/65a48b9e-1f8c-11e7-9565-a530d4a380d8.png)

Code:
[blogapp-crash.zip](https://github.com/treefrogframework/treefrog-framework/files/916448/blogapp-crash.zip)

Config:
OS: Windows 10
MSVC 2015 x86
Qt 5.8.0
Qt Creator 4.2.1
TreeFrog 1.16.0

MultiProcessingModule=thread

Qt Creator Run Settings
Executable: C:\TreeFrog\1.16.0\bin\tadpoled.exe
Arguments: --debug -e dev C:\Users\Administrator\Documents\QtProjects\blogapp

Qt Creator Build Settings
PATH = ..;C:\TreeFrog\1.16.0\bin
TFDIR = C:\TreeFrog\1.16.0

**Comment by treefrogframework** [comment]
publish() function sends messags to treefrog (tfmanager) process, so doesn't work without treefrog process.
You can attach tadpole process for debugging after excuting "treefrogd -e dev".

**Comment by AmiArt** [comment]
Attached to tadpole process and debugging started to work.
Thanks for help !
