### ISSUE TITLE
Status 304 (Not modified) not send for static content

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#141]
This is because If-Modified-Since header doesn't have millisecond resolution
but is compared with FileInfo.lastModified() which may have millisecond part.

Modified a bit tactioncontext.cpp for debugging:
![if_modified_since_header](https://cloud.githubusercontent.com/assets/9396016/25807046/c425bd9a-3405-11e7-9508-a5be650def04.png)

See also:
http://stackoverflow.com/questions/18603154/http-if-modified-since-with-milliseconds#18603265

Environment:
TreeFrog 1.16.0, Qt 5.8
MSVC++ 2015 x86
Windows 10

**Comment by treefrogframework** [comment]
Thanks!
Try 43d022c67fb

**Comment by AmiArt** [comment]
It works :) Thanks for help.
