### ISSUE TITLE
Missing clientAddress() in TWebSocketEndpoint

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#144]
There is no way to get IP address of remote peer in TWebSocketEndpoint class.

Can we add clientAddress() method to TWebSocketEndpoint, or just pass THttpRequest to onOpen() as second parameter ? THttpRequest would be also useful to access some GET parameters like token: 

ws://127.0.0.1/chat?token=1234

See Qt5.8 class:
QWebSocket::request()
QWebSocket::requestUrl()
QWebSocket::peerAddress()
QWebSocket::peerPort()

**Comment by treefrogframework** [comment]
Implemented in 4b9110b3230c98215ae8083fbb4027e2892adabf

**Comment by AmiArt** [comment]
Thanks !
