### ISSUE TITLE
MongoDB needs support for custom documents' Id

### ISSUE THREAD

**Issue by fro0m** [treefrogframework/treefrog-framework#145]
When creating new Document in Mongo Database it generates Id by framework, however there is a need to add random Ids, not generated by framework.

**Comment by treefrogframework** [comment]
Concrete  idea?

**Comment by fro0m** [comment]
@treefrogframework  for example if I use only REST interface of server and data contains of for example name : "hello" and id: { uid: 15, itemId : 444} I want that this item to be saved with come in Id.
may be I do something wrong, but if I try to save this id to mongo object, this item still will have Id generated by mongo.

**Comment by treefrogframework** [comment]
I don't understand problem you point out.
What API do you need?

See http://treefrogframework.github.io/treefrog-framework/user-guide/en/model/object-document-mapping-on-mongodb.html
