### ISSUE TITLE
Wrong path to config directory when running as Windows service

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#147]
Installed treefrog as Windows service, but server doesn't start from Service Manager (got error 1)

Install command:
`sc create MyService DisplayName= "MyService" start= auto binPath= "\"C:\TreeFrog\1.17.0\bin\treefrog.exe\" -w -e product \"C:\Users\Administrator\Documents\QtProjects\TreeFrog\"" depend= RpcSs/Tcpip obj= LocalSystem`

It seems that treefrog can't get correct path of config directory.
Treefrog.log and app.log was empty, so I added some file logging.

![1](https://user-images.githubusercontent.com/9396016/27035848-19260afa-4f83-11e7-84ee-a1629c18e07b.png)

In tfmanager\main.cpp on line 492 app.appSettingsFilePath() returns 
`C:/WINDOWS/system32\config\application.ini`

whereas the correct path to application.ini is:
`C:\Users\Administrator\Documents\QtProjects\TreeFrog\config\application.ini`

In TWebApplication::TWebApplication(int &argc, char **argv)
argc: 1
argv[0]: ''
webRootAbsolutePath: C:/WINDOWS/system32\

Config:
Windows 10 x64
Qt 5.9 + MSVC 2015 x32
TreeFrog 1.17.0

**Comment by hks2002** [comment]
You must start your Treefrog service from you application root directory. 
It seems your Windows service is start from C:/WINDOWS/system32\, so you get the wrong path.

You can go in to the application root directory first, then run "treefrog -d" command, option "-d"" means Treefrog run as a service.

**Comment by AmiArt** [comment]
Thanks for reply, but this doesn't solve the problem.
Option -d runs treefrog as daemon, but I want to start it as service (option -w), so it will start event if nobody is logged in to Windows.

**Comment by hks2002** [comment]
Maybe you can try to create one .bat file. 
Then set the .bat file run automatically.

**Comment by treefrogframework** [comment]
Fixed in bda16aa388efafb9d9600c0dfeac367d178b132d.
Could you test it?

**Comment by AmiArt** [comment]
Not tested yet, but i see that parseArguments() function was added.
Can you explain why don't you use CommandLineToArgvW() ?
Not sure if  parseArguments() can parse arguments exactly like Windows API does... 

And there is memory leak in winServiceMain():
``` 
if (!pathstr.isEmpty()) {
        auto argList = parseArguments(pathstr);
        auto *args = new char*[argList.count()];      // args is not freed

        for (int i = 0; i < argList.count(); i++) {
            args[i] = argList[i].data();
        }
        ret = managerMain(argList.count(), args);
}
```

**Comment by AmiArt** [comment]
Works, thank you.
