### ISSUE TITLE
Database connection leak in TSqlDatabasePool

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#148]
To reproduce this bug just stop database server when treefrog is running, and then refresh any page that load some data from db.

In treefrog.log there will be some database open errors, each one with different connection name: rdb00_xx,
indicating that treefrog each time gets another db from pool.

```
ERROR [3264] SQL database open error: rdb00_23
WARN  [3264] QSqlQuery::exec: database not open (kernel\qsqlquery.cpp:391 bool __thiscall QSqlQuery::exec(const class QString &))
ERROR [14784] SQL database open error: rdb00_22
WARN  [14784] QSqlQuery::exec: database not open (kernel\qsqlquery.cpp:391 bool __thiscall QSqlQuery::exec(const class QString &))
```

Refresh page until connection name drops to rdb00_00 - its the last connection from pool, the next requests from browser will not be executed, because there is no connection available. In Task Manager tadpole.exe is using 100% of CPU. Database server restart doesn't help.

Database leak occurs in TsqLDatabasePool::database():
![1](https://user-images.githubusercontent.com/9396016/27079581-75ff3b10-5038-11e7-96cc-b9380a1a1d88.png)

Config:
Windows 10 x64
Qt 5.9 + MSVC 2015 x32
TreeFrog 1.17.0
PostgreSQL 9.6

**Comment by treefrogframework** [comment]
Thanks for detailed reporting. I could fix the bug instantly.
Fixed in 716bb4341167630fabb2f7765305b2fd18e6dc06.
