### ISSUE TITLE
Add numberOfSubscibers() method to TScheduler class

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#150]
I use TScheduler class to periodically poll database for some data.
But I don't want to pool database if there are no subscribers.
Currently there is no way to get the number of subscribers of specific topic.

**Comment by treefrogframework** [comment]
It's difficult to implement it in TreeFrog side, because two or more app server processes exist, which each have subscribers.

I think that storing the counter into DB is needed. Can implement in web app side.
