### ISSUE TITLE
cannot compile tools in FreeBSD 10/11 with gcc or clang

### ISSUE THREAD

**Issue by terenceso** [treefrogframework/treefrog-framework#154]
When run make in "treefrog-framework-1.18.0/tools", I got following message:
`cd tfmanager/ && ( test -e Makefile || /usr/local/lib/qt5/bin/qmake /root/treefrog-framework-1.18.0/tools/tfmanager/tfmanager.pro -spec freebsd-g++ CONFIG+=release 'target.path="/usr/local/bin"' 'header.path="/usr/local/include/treefrog"' 'datadir="/usr/local/share/treefrog"' 'lib.path="/usr/local/lib"' -o Makefile ) && make -f Makefile
g++ -Wl,-O1 -pthread -Wl,-rpath,/usr/local/lib/qt5 -o treefrog main.o  servermanager.o  systembusdaemon.o  moc_servermanager.o  moc_systembusdaemon.o   -L/usr/local/lib -Wl,-rpath,/usr/local/lib -ltreefrog -L/usr/local/lib/qt5 -lQt5Network -lQt5Core
main.o: In function `TreeFrog::runningApplicationPid(QString const&)':
main.cpp:(.text+0x1031): undefined reference to `TProcessInfo::processName() const'
main.o: In function `TreeFrog::managerMain(int, char**)':
main.cpp:(.text+0x390a): undefined reference to `TProcessInfo::terminate()'
main.cpp:(.text+0x444f): undefined reference to `TProcessInfo::kill()'
main.cpp:(.text+0x46bb): undefined reference to `TProcessInfo::restart()'
/usr/local/lib/libtreefrog.so: undefined reference to `TProcessInfo::exists() const'
/usr/local/lib/libtreefrog.so: undefined reference to `TProcessInfo::allConcurrentPids()'
/usr/local/lib/libtreefrog.so: undefined reference to `TProcessInfo::ppid() const'
collect2: error: ld returned 1 exit status
*** Error code 1`

I did try on both FreeBSD 10.4 and 11.0 with clang / GCC, and got the same result!

**Comment by treefrogframework** [comment]
Maybe fixed in f8f0065950b28cef91039c7de7ebc79827e47478.

Could you try it?

Set this.
  export QMAKESPEC=freebsd-clang

**Comment by terenceso** [comment]
I will try your suggestion later! but I also tried GCC COMPILER and got the same result.

**Comment by terenceso** [comment]
with the latest source code from git, it can be compiled and installed in FreeBSD 11 with clang!
_cd treefrog-framework
env QMAKESPEC=freebsd-clang ./configure --prefix=/usr/local
cd src
env QMAKESPEC=freebsd-clang make
env QMAKESPEC=freebsd-clang make install
cd ..
cd tools
env QMAKESPEC=freebsd-clang make
env QMAKESPEC=freebsd-clang make install_
