### ISSUE TITLE
Way to change TREEFROG_DATA_DIR for tspawn at runtime

### ISSUE THREAD

**Issue by cheese** [treefrogframework/treefrog-framework#157]
We are packaging treefrog-framework for Fedora, and we want to run the releasetest during packaging.

But in the build environment, the data files to be installed to /usr/share/treefrog are not actually installed there. Instead, that will be a path like ~/rpmbuild/BUILDROOT/treefrog-framework-1.18.0-1.fc26.x86_64/usr/share/treefrog/ .
So tspawn won't find the defaults data and releasetest will fail.

So, it is a good idea to instruct tspawn to find defaults data in another path, through environment variable or command line instruction.

**Comment by treefrogframework** [comment]
Couldn't you ignore the releasetest for packaging?
I cannot find a reason to modify tspawn command for Fedora packaging only.

**Comment by cheese** [comment]
Of course the test can be ignored.
This is a common situation of packaging for Linux distributions. No limited to Fedora.
