### ISSUE TITLE
jscontext test coredump on Fedora 26 x86_64

### ISSUE THREAD

**Issue by cheese** [treefrogframework/treefrog-framework#158]
$ src/test/testall.sh
....
Testing jscontext/jscontext ...
********* Start testing of JSContext *********
Config: Using QtTest library 5.7.1, Qt 5.7.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.1.1 20170622 (Red Hat 7.1.1-3))
PASS   : JSContext::initTestCase()
PASS   : JSContext::eval(01)
PASS   : JSContext::eval(02)
PASS   : JSContext::eval(03)
PASS   : JSContext::eval(04)
PASS   : JSContext::callAsConstructor(01)
PASS   : JSContext::callAsConstructor(02)
PASS   : JSContext::require(01)
PASS   : JSContext::callFunc(01)
PASS   : JSContext::callFunc(02)
PASS   : JSContext::callFunc(03)
PASS   : JSContext::callFunc1(01)
PASS   : JSContext::callFunc1(02)
PASS   : JSContext::transform(01)
PASS   : JSContext::transform(02)
PASS   : JSContext::transform(03)
PASS   : JSContext::load(01)
PASS   : JSContext::load(02)
PASS   : JSContext::load(03)
PASS   : JSContext::react(01)

========= Received signal, dumping stack ==============

**coredumpctl output:**

           PID: 19390 (jscontext)
           UID: 1000 (cheese)
           GID: 1000 (cheese)
        Signal: 6 (ABRT)
     Timestamp: Fri 2017-08-04 11:26:41 CST (1min 33s ago)
  Command Line: ./jscontext
    Executable: /home/cheese/rpmbuild/BUILD/treefrog-framework-1.18.0/src/test/jscontext/jscontext
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (cheese)
       Boot ID: bec70b3ba19f4beda2b6f095e426cfe8
    Machine ID: 1d1e4dbb677b42f6b5544bf5a9c08bec
      Hostname: wstest-lirb
       Storage: /var/lib/systemd/coredump/core.jscontext.1000.bec70b3ba19f4beda2b6f095e426cfe8.19390.1501817201000000.lz4
       Message: Process 19390 (jscontext) of user 1000 dumped core.
                
                Stack trace of thread 19392:
                #0  0x00007ff4b21e766b raise (libc.so.6)
                #1  0x00007ff4b21e9470 abort (libc.so.6)
                #2  0x00007ff4b30e7527 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                #3  0x00007ff4b34ec583 _ZN5QTest18FatalSignalHandler6signalEi (libQt5Test.so.5)
                #4  0x00007ff4b2e492c0 __restore_rt (libpthread.so.0)
                #5  0x00007ff4a8064221 n/a (n/a)
                #6  0x00007ff4b36dee86 _ZN3QV414ScriptFunction4callEPKNS_7ManagedEPNS_8CallDataE (libQt5Qml.so.5)
                #7  0x00007ff4b36dbf0d _ZN3QV417FunctionPrototype12method_applyEPNS_11CallContextE (libQt5Qml.so.5)
                #8  0x00007ff4b36dc3b6 _ZN3QV415BuiltinFunction4callEPKNS_7ManagedEPNS_8CallDataE (libQt5Qml.so.5)
                #9  0x00007ff4b3747b65 _ZN3QV47Runtime12callPropertyEPNS_15ExecutionEngineEiPNS_8CallDataE (libQt5Qml.so.5)
                #10 0x00007ff4a805e3ce n/a (n/a)
                #11 0x00007ff4b36dee86 _ZN3QV414ScriptFunction4callEPKNS_7ManagedEPNS_8CallDataE (libQt5Qml.so.5)
                #12 0x00007ff4b3747b65 _ZN3QV47Runtime12callPropertyEPNS_15ExecutionEngineEiPNS_8CallDataE (libQt5Qml.so.5)
                #13 0x00007ff4a2f9b8de n/a (n/a)
                #14 0x00007ff4b37031fa _ZN3QV46Script3runEv (libQt5Qml.so.5)
                #15 0x00007ff4b3641ed8 _ZN9QJSEngine8evaluateERK7QStringS2_i (libQt5Qml.so.5)
                #16 0x00007ff4b3a57f94 _ZN9TJSModule8evaluateERK7QStringS2_i (/home/cheese/rpmbuild/BUILD/treefrog-framework-1.18.0/src/libtreefrog.so.1.18.0)
                #17 0x00000000004085b2 _ZN9JSContext5reactEv (jscontext)
                #18 0x00007ff4b32ab3d2 _ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_ (libQt5Core.so.5)
                #19 0x00007ff4b34f302a _ZNK5QTest11TestMethods16invokeTestOnDataEi (libQt5Test.so.5)
                #20 0x00007ff4b34f3d60 _ZNK5QTest11TestMethods10invokeTestEiPKcPNS_8WatchDogE (libQt5Test.so.5)
                #21 0x00007ff4b34f42d1 _ZNK5QTest11TestMethods11invokeTestsEP7QObject (libQt5Test.so.5)
                #22 0x00007ff4b34f48d3 _ZN5QTest5qExecEP7QObjectiPPc (libQt5Test.so.5)
                #23 0x00007ff4b34f4f12 _ZN5QTest5qExecEP7QObjectRK11QStringList (libQt5Test.so.5)
                #24 0x0000000000409055 _ZZ4mainEN6Thread3runEv (jscontext)
                #25 0x00007ff4b30f8c9e _ZN14QThreadPrivate5startEPv (libQt5Core.so.5)
                #26 0x00007ff4b2e3e36d start_thread (libpthread.so.0)
                #27 0x00007ff4b22c1b8f __clone (libc.so.6)
                
                Stack trace of thread 19393:
                #0  0x00007ff4b2e44d1a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007ff4b30f92e3 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                #2  0x00007ff4b34f5142 _ZN5QTest8WatchDog3runEv (libQt5Test.so.5)
                #3  0x00007ff4b30f8c9e _ZN14QThreadPrivate5startEPv (libQt5Core.so.5)
                #4  0x00007ff4b2e3e36d start_thread (libpthread.so.0)
                #5  0x00007ff4b22c1b8f __clone (libc.so.6)
                
                Stack trace of thread 19390:
                #0  0x00007ff4b2e4481b pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007ff4b30f93fb _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
                #2  0x00007ff4b30f88de _ZN7QThread4waitEm (libQt5Core.so.5)
                #3  0x0000000000403f18 main (jscontext)
                #4  0x00007ff4b21d14da __libc_start_main (libc.so.6)
                #5  0x0000000000403fba _start (jscontext)

**Comment by cheese** [comment]
This issue only occurs in Fedora 25 and 26, currently with Qt 5.7.1, but does not occur in Fedora 27(rawhide), currently with Qt 5.9.1, and CentOS7, currently with Qt 5.6.1.

**Comment by treefrogframework** [comment]
Use the latest Qt.
