### ISSUE TITLE
Increase wait time for stopping treefrog daemon

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#160]
When I use command 'treefrog.exe -k stop <application_dir>' I always get message:

`TreeFrog application servers shutdown failed`

after 10 seconds. But my treefrog daemon needs ~13 sec to stop (I use both HTTP and WebSockets connections). Please increase time in waitForTerminated() (tools/tfmanager/main.cpp, line 384).

Config:
Windows 10
TreeFrog 1.18.0
Qt 5.9 + MSVC2015 x32

**Comment by treefrogframework** [comment]
If keeping connections such as websocket, app server cannot stop. 
You can run "treefrog.exe -k abort" or modify the source code yourself locally.

**Comment by AmiArt** [comment]
Thanks for help, I did as you suggested.
