### ISSUE TITLE
HTTP 500 status code sent for empty files

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#161]
To reproduce this bug:
1. Create empty file in TreeFrog /public directory named empty.txt
2. Visit URL http://localhost:8800/empty.txt in web browser

**Comment by treefrogframework** [comment]
Not reproduced in my environments, both Linux and Windows10.
Returns status code 200.

**Comment by AmiArt** [comment]
You are right. Sorry for misleading description.
I forgot that all my files are served by custom StaticContentController class and when it returns response with empty body (empty file), Treefrog treat this as error and sets status code to 500.
