### ISSUE TITLE
Allow access to POSTed data other than 'application/json' and 'application/x-www-form-url-encoded'

### ISSUE THREAD

**Issue by proostas** [treefrogframework/treefrog-framework#162]
Now the handler just ignores other types with `tSystemWarn("unsupported content-type: %s", qPrintable(ctype));`

But it would be more flexible to give a user (especially if Treefrog is used as an application server) the opportunity to decide what to do with the raw unknown data without trying to parse it. Maybe write it to a file and store the path `httpRequest()->rawDataPath()` or something like that. To prevent possible system overload or DDoS attacks, it could be configurable in the config file, e.g. `StoreUnknownTypesOnDisk=true`, with default false.

It would be a nice improvement as it doesn't make TreeFrog support a particular type internally and allows devs to deal with as many custom types as they can think about. That is, your type - your responsibility how to parse it.

**Comment by aoym** [comment]
I will consider your suggestion.

**Comment by treefrogframework** [comment]
I will consider your suggestion.

**Comment by treefrogframework** [comment]
See e1fb959.
Is there type other than 'application/json' and 'application/x-www-form-url-encoded' in HTML?

Any type can be allowed, but it makes sense really?

**Comment by proostas** [comment]
Thank you! I think this is actually enough. What I really needed in the access to the raw body.

Yes, for HTML these are all there is. But for a custom application, e.g. a Qt/QML one, sometimes it's much simpler to send data without wrapping it in multipart/form-data. It's useless to prepare a proper multipart/form-data to send a single png to a server, for example. Or, alternatively, one could exchange data in a custom super-compact binary format, via 'application/octet-stream'. Or, one could even send a compressed json without much fuss. That is, if a client and a server speak the same "language", then one could deviate from the standard HTML ways of exchanging information.
