### ISSUE TITLE
All helper header auto included in to each view source file.

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#163]
tmake auto include all helper header to all views source file. 
Even all validators, one validator is normally used for one form. 
maybe let developer manually include these helper headers as required is better.

**Comment by hks2002** [comment]
if you have many view files, such as 500, add several validators or helplers will let compile process take a lot of time, became very slowly.

**Comment by aoym** [comment]
Any idea for implementation of the framework?

**Comment by treefrogframework** [comment]
Any idea for implementation of the framework?

**Comment by hks2002** [comment]
ErbConverter ignore all helper files, delete codes related to helpersDirectory.

**Comment by treefrogframework** [comment]
If so, some view files that was compiled successfully will fail to be compiled.

**Comment by hks2002** [comment]
I strongly suggest manually add helper header to view files(erb or otama) as required. it could also compile successfully.

Reason:
I created one helper named "util", and function/method defined in util only used in index.erb. rather then all four view(index.erb, show.erb, edit.erb, delete.erb),  include "util.h" in index.erb is enough.
and, not all controller views (index.erb) need "util" function/method.

especially, validators are in helper directory. there must be many validators in one project, normally one validator is for one controller, all validators header add to all view files looks so unacceptable.

By default, there is only one helper named "ApplicationHelper", that will not have obvious influence.
Suppose there is such a situation: 100 validator helper, 1000 controller views.

**Comment by hks2002** [comment]
perhaps leave only one ApplicationHelper is a good idea.

**Comment by treefrogframework** [comment]
Thanks.
I can understand your suggestion, but will keep the current spec.
Including header files in views is a hassle.

**Comment by hks2002** [comment]
Could you consider add one comment option in .pro, 
#DEFINE+=DONOT_INCLUDE_ALL_HELPERHEADER_TO_VIEW
then add logic to that codes using 
```C++
#ifdef DONOT_INCLUDE_ALL_HELPERHEADER_TO_VIEW
    //new codes
#else
  //old codes
#endif
```
My project have 270 validators and  1100 view now. I really don't want to use current spec.
every time I modify/change/create one validator, compile.......... compile....... compile.......

If you agree with this, i'll pull a new request.
let developer could have a second choice by uncomment DEFINE+=DONOT_INCLUDE_ALL_HELPERHEADER_TO_VIEW
