### ISSUE TITLE
Treefrog running as Windows Service not stopped correctly

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#164]
Sometimes when Treefrog service is stopped from SCM, service status changes to STOPPED, but treefrog.exe process is still running for about 30 seconds. This happens very rarely (1 in 10 times or less)

I spent last two days to track this bug and found that the code executed after call SetServiceStatus(statusHandle, SERVICE_STOPPED) in winServiceMain() might not be executed at all,
so not all resources/locks might be freed by Treefrog.

According to MSDN documentation:

> Do not attempt to perform any additional work after calling SetServiceStatus with SERVICE_STOPPED, because the service process can be terminated at any time.

Link:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686241(v=vs.85).aspx

Here is current implementation of Treefrog winServiceMain():

```
void WINAPI winServiceMain(DWORD, LPTSTR *)
{
    // ...

    // Service status
    serviceStatus.dwCurrentState = SERVICE_RUNNING;
    SetServiceStatus(statusHandle, &serviceStatus);

    // Main function
    // ....

    // Service status
    serviceStatus.dwCurrentState = SERVICE_STOPPED;
    serviceStatus.dwWin32ExitCode = ret;
    SetServiceStatus(statusHandle, &serviceStatus);
    tSystemInfo("Windows service stopped");            <-- This code might not be executed
}
```

I added the following lines after tSystemInfo("Windows service stopped") for debugging:

```
    QFile f("D:/file.txt"); 
    if (f.open(QIODevice::WriteOnly))
    {
        f.write("test");
        f.flush();
    }
```

and file.txt sometimes was created, sometimes not, and sometimes it was empty.

So I suggest to print message and close system log before SetServiceStatus(), like this:

```
void WINAPI winServiceMain(DWORD, LPTSTR *)
{
    // ...

    // Service status
    serviceStatus.dwCurrentState = SERVICE_RUNNING;
    SetServiceStatus(statusHandle, &serviceStatus);

    // Main function
    // ....

    tSystemInfo("Windows service stopped");
    Tf::releaseSystemLogger();

    // Service status
    serviceStatus.dwCurrentState = SERVICE_STOPPED;
    serviceStatus.dwWin32ExitCode = ret;
    SetServiceStatus(statusHandle, &serviceStatus);
}
```

And add check:
```
if (!isOpen())
 return;
```
at the beginning of TFileAioWriter::close() to prevent it to execute from destructor of systemLog global variable.

Service install command:
`sc create MyService DisplayName= "MyService" start= auto binPath= "\"C:\TreeFrog\1.18.0\bin\treefrog.exe\" -w -e product \"C:\Users\Administrator\Documents\QtProjects\TreeFrog\MyServiceProject"" depend= RpcSs/Tcpip obj= LocalSystem`

Config:
Windows 10
Treefrog 1.18.0
MSVC2015 + Qt 5.9

**Comment by treefrogframework** [comment]
Let me see your pull-request.
