### ISSUE TITLE
HTTP 304 response must not contain message-body

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#168]
See explanation:
https://serverfault.com/questions/168345/sending-content-message-body-along-with-304-not-modified-header

Also Content-Type and Content-Lenght should not be sent - see what headers are sent by Apache HTTP Server.

**Comment by aoym** [comment]
fixed in 31bbb938dd34b6a55b4829f5445f4.

**Comment by AmiArt** [comment]
Thank you
