### ISSUE TITLE
Socket write error message in log when sending empty response body

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#170]
I get warnings in app.log:

> 2017-08-30 13:58:27.639 WARN  [11144] socket write error: total:0 (0)
> 2017-08-30 14:01:45.563 WARN  [11352] socket write error: total:0 (0)
> 2017-08-30 14:05:45.497 WARN  [12580] socket write error: total:0 (0)
> 2017-08-30 14:08:22.743 WARN  [13944] socket write error: total:0 (0)
> 2017-08-30 14:14:01.300 WARN  [13944] socket write error: total:0 (0)

when I set empty response body in my controller:

`httpResponse().setBody(QByteArray(""));
`

The problem is in the following code (thttpsocket.cpp, line 139):

```
qint64 written = QTcpSocket::write(data + total, qMin(size - total, WRITE_LENGTH));
if (Q_UNLIKELY(written <= 0)) {
    tWarn("socket write error: total:%d (%d)", (int)total, (int)written);
    return -1;
}
```

Please change condition from:
`if (Q_UNLIKELY(written <= 0)) {`
to:
`if (Q_UNLIKELY(written < 0)) {`

QTcpSocket::write(const char *data, qint64 maxSize) returns -1 on error, see Qt documentation.

**Comment by aoym** [comment]
try 31bbb938dd34b6a55b4829f5445f4.

**Comment by AmiArt** [comment]
Works, thanks
