### ISSUE TITLE
Question: TFSESSION string very long when store with cookie, is it normal?

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#176]
Set-Cookie:TFSESSION=0000000b000000400065003200620032003600640039003400370034003000310061003900630039003400330062003500330038003800390034003800370036003600340064003900000002000000000100000040006400350061003600620032006400370062006400390066003400370063003900340066006500340065003500350030006200620065006400630063003200630000000200000000010000001a00630075007200720065006e00740055007300650072005a00680000000a00000000067ba1740654580000001a00630075007200720065006e00740055007300650072004900640000000200000000010000001a00630075007200720065006e007400550073006500720045006e0000000a000000000a00410064006d0069006e0000001c005f006c006f00670069006e0055007300650072004e0061006d00650000000a000000000a00610064006d0069006e0000000e005f0063007300720066004900640000000c0000000028613064373966373534613637346438303435313738653362333962353662333633383965393632330000004000340036003100350039006600360035003200380030003500340034003300320035003400310061006500320030003700650061003800370032003800300065000000020000000001000000400033006300650036006300640039006200620064003000640030003900380065003200320031006400330038003900610039006300610038006300640064003000000002000000000100000040003200650061003300660039003900330037006300650064003200630036003100340038003100310033003600390036003000610066003300320031003800320000000200000000010000004000320031006300650033006600310065003100630063006300350035003000300032003900610064003300640038003600640061003300380030003000320038000000020000000001_e6004daf1bc67dc79a0add5deaf256d1b0069dc0; HttpOnly; path=/

**Comment by treefrogframework** [comment]
It is correct, a cookie session.
See http://www.treefrogframework.org/en/user-guide/controller/session.html

**Comment by hks2002** [comment]
Thanks.
