### ISSUE TITLE
Csrf + ajax

### ISSUE THREAD

**Issue by mobilemindtec** [treefrogframework/treefrog-framework#177]
Hi!

I'm getting this exception `Caught SecurityException: Invalid authenticity token` but I do not know what happening.

1 - Enable csrf protection
2 - Render the view "a"
3 - Call ajax another view "b" to populate select
4 - Post "a" data, without ajax
5 - the exception is throw

This did should work, right? It looks like the ajax call to view "b" is changeging the view "a" csrf token.

Thanks!

**Comment by treefrogframework** [comment]
An authenticity token of last view, "b" in this case, must be sent always in current spec.
You can get the value of the token with authenticityToken() function.

**Comment by mobilemindtec** [comment]
Ok, thanks!
