### ISSUE TITLE
Get raw body

### ISSUE THREAD

**Issue by mobilemindtec** [treefrogframework/treefrog-framework#179]
How do I get the raw body from HttpRequest? I need to implement hmac validation on json data, also to generate a hash I need the original raw json content. If I extract the hmac hash from `httpRequest().jsonData()` it fails, because `json.toBinaryData()` fields' order is different than received. Can I get the raw body data from HttpRequest?

Thanks!

**Comment by proostas** [comment]
Currently, the body gets discarded. I've feature-requested the preservation of the original body [here](https://github.com/treefrogframework/treefrog-framework/issues/162).

**Comment by treefrogframework** [comment]
Implmented in e1fb959c8875182cae941401a0c82276e678d385.
Test it.

**Comment by mobilemindtec** [comment]
Ok, its work. thanks!
