### ISSUE TITLE
Missing include files when building unit test

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#180]
I created unit test for my project following the directions on this page:
http://www.treefrogframework.org/en/user-guide/test/

But when I build it, I get this error:
![tf1](https://user-images.githubusercontent.com/9396016/32445182-4860776a-c305-11e7-9957-2cfe4aca40d9.png)

I checked TFDIR\include directory, and there is no tkvsdatabasepool.h and tsqldatabasepool.h files.
It seems that qmake && nmake install commands don't copy these files from src directory.

Config:
Windows 10 x64
TreeFrog 1.19.0

**Comment by treefrogframework** [comment]
try in c32d13e67c24808ed9ac4a34a4c1d1c30290e8b7.

**Comment by treefrogframework** [comment]
try in a631e69473c3c13aa77dce80714c14d93930a851.

**Comment by AmiArt** [comment]
Fixed. Thanks a lot for help!
