### ISSUE TITLE
Suggestion: new TrimMode for <script type="text/javascript">js code</script>

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#181]
If write some js code directly with  <script type="text/javascript">js code</script> in ERB,  in order to make them readable, normally these js code is beautified/tidied, the result is a lot blank space or tab in each line of the js code.  all blank space or tab of these js code be take into c++ source file also.
so i think, if tamke could remove them, the source file would be shorter and clean.

**Comment by treefrogframework** [comment]
Try setting ’2’ to .trim_mode file in the view directory?

**Comment by hks2002** [comment]
Thanks, my expect is achieved by trim_mode 2. I confirmed it.
