### ISSUE TITLE
Help: error LNK2019 using Qt 5.9.2 with msvc2017-x86. 

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#183]
Once include one sqlobjects header to one controller source file, "error LNK2019 : unresolved external symbol" comes out.  
what should I do?  I just feel using mingw32-make compile is too slowly, so I try to use ms nmake.

**Comment by treefrogframework** [comment]
Try in 6451479a3db363410c9b1e39ab661f9bedc6d036.
