### ISSUE TITLE
missing files when using TfTest

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#185]
Missing these files:
thazardptr.h/thazardobject.h/tstack.h/tkvsdatabasepool.h/tsqldatabasepool.h 
I need copy them form the src folder  to the install folder.
please confirm it.

**Comment by AmiArt** [comment]
Hi hks2002,
I have the same problem, see ticket #180.

**Comment by hks2002** [comment]
my Config:
Windows 10 x86
TreeFrog 1.20.0

after I copyed thazardptr.h/thazardobject.h/tstack.h/tkvsdatabasepool.h/tsqldatabasepool.h to TFDIR/include 
it still need add **QT+=xml** to .pro, because it used QDomDocument.
then, the unit test works.

**Comment by treefrogframework** [comment]
see #180.
