### ISSUE TITLE
should return 500 or 404? when access a url with a doesn't exist action(current return 500).

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#187]
such as, Acontroller have 2 actions: B/C,
if access url A/D, D is not a action. the status is 500, rather 404. 
Does this should be change?  
Sometimes, source code is typing error in the url , if status is 404, could let develop more quickly found the error.

**Comment by AmiArt** [comment]
Shouldn't the ticket be called 'return 404 rather 500...' ?

**Comment by hks2002** [comment]
@AmiArt changed the ticket.

**Comment by treefrogframework** [comment]
Fixed in af760f050e077f79427a7783bc47fda2dd520736.
Try it out.

**Comment by AmiArt** [comment]
The fix works for me. Thanks.

**Comment by hks2002** [comment]
fixed.
