### ISSUE TITLE
need sqlormapper new function setSelectedFields

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#188]
current sqlormapper  all ways get all fields from a table when run query.
in case the table have many fields, but you just want to one or two, current ormapper's query get too many  unnecessary fileds. 
so if the ormapper could set the fields you want to get, could  improve the performance.

**Comment by hks2002** [comment]
Create a view in database directly?

**Comment by treefrogframework** [comment]
To get all fields of a table is the specification of TSqlORMapper.
If the performance is important, you should use TSqlQuery class.

**Comment by hks2002** [comment]
Thanks.
