### ISSUE TITLE
ApplicationController::staticRelease() method should be called when event loop is available

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#189]
This is because there is no way to free resources of job schedulers.

Since there is no official example of TScheduler class I had to find myself how to start and stop job schedulers. So I tried the following ways:

First, my job scheduler:

```
class MyScheduledJob : public TScheduler
{
public:
     MyScheduledJob(QObject *parent=NULL) : TScheduler(parent) {
        tInfo("MyScheduledJob");
     }
  ~MyScheduledJob() {
        tInfo("~MyScheduledJob");
    }

protected:
    void job() {
        tInfo("MyScheduledJob::job()");
    }
}
```

**Case 1. Declare job scheduler as member of ApplicationController.**

This doesn't work - the docs says that the controller should not have member variables (last paragraph of http://www.treefrogframework.org/en/user-guide/controller/)

**Case 2. Declare job scheduler as static member in ApplicationController:**

```
class T_CONTROLLER_EXPORT ApplicationController : public TActionController
{
    Q_OBJECT
public:
    ApplicationController()
        : TActionController() { }
public slots:
    void staticInitialize();
    void staticRelease();
private:
    static MyScheduledJob m_myScheduledJob;
};

MyScheduledJob ApplicationController::m_myScheduledJob;

void ApplicationController::staticInitialize()
{
    m_myScheduledJob.start(60*1000);
}
void ApplicationController::staticRelease()
{
    m_myScheduledJob.stop();
}
```
The above code crashes my unit test at startup when controller.dll is loaded - I link my unit test with controller library (mytest.pro):

LIBS += -L$$PWD/../lib -lcontroller -lhelper -lmodel -lview

**Case 3. Declare job scheduler as static pointer member in ApplicationController:**

```
class T_CONTROLLER_EXPORT ApplicationController : public TActionController
{
    Q_OBJECT
public:
    ApplicationController()
        : TActionController() { }
public slots:
    void staticInitialize();
    void staticRelease();
private:
    static MyScheduledJob *m_myScheduledJob;
};

MyScheduledJob ApplicationController::*m_myScheduledJob = NULL;

void ApplicationController::staticInitialize()
{
    m_myScheduledJob = new MyScheduledJob();
    m_myScheduledJob->start(60*1000);
}
void ApplicationController::staticRelease()
{
    m_myScheduledJob->stop();
    delete m_myScheduledJob;
}
```

This works, but I get the following warning in treefrog.log:

> WARN  [7760] QObject::killTimer: Timers cannot be stopped from another thread (kernel\qobject.cpp:1688 void __thiscall QObject::killTimer(int))
> WARN  [7760] QObject::~QObject: Timers cannot be stopped from another thread (kernel\qobject.cpp:247 __thiscall QObjectPrivate::~QObjectPrivate(void))

**Case 4. Same as case 3 but use deleteLater() instead of delete.**

```
MyScheduledJob ApplicationController::*m_myScheduledJob = NULL;

void ApplicationController::staticInitialize()
{
        m_myScheduledJob = new MyScheduledJob();
        m_myScheduledJob->start(60*1000);
}
void ApplicationController::staticRelease()
{
    m_myScheduledJob->stop();
    m_myScheduledJob->deleteLater();
}
```

Works, but the destructor of MyScheduledJob is not called and causes a memory leak.
This is because the staticRelease() is called when the main event loop has already stopped (see http://doc.qt.io/qt-5/qobject.html#deleteLater)

**My suggested solution:**

In order the case 4 to work the ApplicationController::staticRelease() should be called when event loop is still running, possibly by connecting to QCoreApplication::aboutToQuit() signal (http://doc.qt.io/qt-5/qcoreapplication.html#aboutToQuit).

The change should be done in main():
https://github.com/treefrogframework/treefrog-framework/blob/master/tools/tfserver/main.cpp

```
int main(int argc, char *argv[])
{
    TWebApplication webapp(argc, argv);
    TApplicationServerBase *server = 0;

    // ....

    if (!server->start(debug)) {
        tSystemError("Server open failed");
        fprintf(stderr, "Server open failed\n");
        goto finish;
    }

    ret = webapp.exec();        // runs the event loop
    server->stop();             // this calls ApplicationController::staticRelease(),
                                // when the event loop has already stopped.
                                // SUGGESTED SOLUTION:
                                // Try change these lines to (not tested):
                                //  connect(&webapp, SIGNAL(aboutToQuit()),
                                            server, SLOT(deleteLater()));
                                // ret = webapp.exec(); 
                                // and make sure the the destructor of server
                                // ~TThreadApplicationServer() calls stop()
finish:
    // Release loggers
    Tf::releaseAppLoggers();
    Tf::releaseQueryLogger();
    Tf::releaseAccessLogger();
    Tf::releaseSystemLogger();

    _exit(ret);
    return ret;
}
```
BTW: There is no `delete server` after `server->stop() `- another memory leak ?

**Comment by treefrogframework** [comment]
Fix in e570021.
Try it.

```
MyScheduledJob ApplicationController::*m_myScheduledJob = NULL;

void ApplicationController::staticInitialize()
{
    m_myScheduledJob = new MyScheduledJob();
    m_myScheduledJob->moveToThread(Tf::app()->thread());   // add!
      :
}
```

**Comment by AmiArt** [comment]
Hi, not tested yet, but any reason not doing `delete server` at the end of main() ?

**Comment by treefrogframework** [comment]
Thanks. 469a0ce3203288f1283f9e1c64a508564346b0a0

**Comment by AmiArt** [comment]
Please undo `delete server`. I found the TThreadApplicationServer is already destroyed 
by the parent object (webapp) and TMultiplexingServer in tmultiplexingserver_linux.cpp, line 35.
So we can't delete it again at the end of main(). 
I apologize for entering you into error.

**Comment by AmiArt** [comment]
Thank you, the fix works, but please remove `delete server`.

**Comment by AmiArt** [comment]
I see you changed so now the server is deleted only for thread MPM - that's fine.
PS. You don't have to check if `server` is not null before calling `delete server` - the `delete` operator already check this.
