### ISSUE TITLE
Add logrotate feature

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#190]
It would be nice if TreeFrog have built-in log rotate functionality. The logs of TreeFrog can grow very fast, especially access.log and query.log, making them impossible to view in any text editor. The TreeFrog could monitor the size of each log file and if it reaches the declared size (maybe a new parameter in config file ?) it renames the current log file to, for example query_n.log, then create a new log file. The old TreeFrog logs could be deleted from disk when the log file modified date is older than n days (possibly another parameter in config file).

**Comment by treefrogframework** [comment]
Logrotate tool could be used.
https://linux.die.net/man/8/logrotate
