### ISSUE TITLE
how to get all table's field column when use setjoin()?

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#191]
Now sqlormapper  template only return one table's field. 
if want to get some fields from joined table and get some fields from  join table also, how to do?
I think if we can use setjoin on two table,  that means we need to get both of them once.

```c++
template <class T>
inline T TSqlORMapper<T>::value(int i) const
{
    T rec;
    if (i >= 0 && i < rowCount()) {
        rec.setRecord(record(i), QSqlError());
    } else {
        tSystemDebug("no such record, index: %d  rowCount:%d", i, rowCount());
    }
    return rec;
}
```
setRecord() ignore  other table's fields, only table T.

**Comment by treefrogframework** [comment]
Cannot.
It's specification.

You could use TSqlQueryORMapper class or TSqlQuery class.

**Comment by hks2002** [comment]
thanks.
