### ISSUE TITLE
Add short information in docs how to debug websockets in QtCreator

### ISSUE THREAD

**Issue by AmiArt** [treefrogframework/treefrog-framework#192]
Recently, there have been several questions on the TreeFrog forum regarding
debugging websockets in QtCreator:

https://groups.google.com/forum/#!topic/treefrogframework/deKoB9FazX4
https://groups.google.com/forum/#!topic/treefrogframework/uvrU52o0IMc

I remember I had the same problem described here: https://github.com/treefrogframework/treefrog-framework/issues/140 

So I thought it would be good if one of the the following pages:

http://www.treefrogframework.org/en/user-guide/debug/
http://www.treefrogframework.org/en/user-guide/websocket/

had a brief information that in order to debug a project containing websockets,
you must start the treefrog server: 
`treefrogd -e dev` 
and then attach to tadpoled process.

So that new users of TreeFrog will not encounter the same problems in the future.

**Comment by treefrogframework** [comment]
Could you send a pull-request for docs/en directory?
We use GitHub Pages and Jekyll for documentation.
https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/

**Comment by AmiArt** [comment]
Pull request #195

**Comment by treefrogframework** [comment]
Merged
