### ISSUE TITLE
项目部署

### ISSUE THREAD

**Issue by AnsonRR** [treefrogframework/treefrog-framework#197]
当我在WindowsServer上部署我的工程的时候，我把Qt的.dll拷贝到了Treefrog/bin下面，把libmysql.dll、qsqlmysql.dll都拷贝到了Treefrog/bin下面，treefrog能正常启动，为什么MYSQL driver总是提示加载失败，我这样做对吗？不对的话，我改如何做，不现在尚不清除treefrog加载库的逻辑？能否告知一下，我只是想联系到你，这是我的邮箱rs472714695@foxmail.com，我希望得到你的回复，非常感谢！

**Comment by AnsonRR** [comment]
我会在不久后把这个ISSUE Close

**Comment by AmiArt** [comment]
See link:
http://www.treefrogframework.org/en/user-guide/deployment/

Copy libmysql.dll to Treefrog/bin and qsqlmysql.dll to Treefrog/bin/sqldrivers.
And make sure you use right version of libmysql.dll (x86/x64).
Hope this helps !

**Comment by AnsonRR** [comment]
OK,Thank you very much,I will confirm and try it.
