### ISSUE TITLE
'TGlobal' file not found

### ISSUE THREAD

**Issue by anvarzkr** [treefrogframework/treefrog-framework#204]
Hello!
I have installed treefrog from installation guide (http://www.treefrogframework.org/en/user-guide/install/).
Then I am trying to compile code on macOS 10.12.

Execution order:
```
qmake -r "CONFIG+=release"
make clean
make
```
After 'make' command I receive the next error:
```
In file included from applicationhelper.cpp:1:
./applicationhelper.h:4:10: fatal error: 'TGlobal' file not found
#include <TGlobal>
         ^
1 error generated.
make[1]: *** [.obj/applicationhelper.o] Error 1
make: *** [sub-helpers-make_first-ordered] Error 2
```
I think I need to insert something into PATH variable but can't imagine what.
Could you help, please?

**Comment by Light-Wizzard** [comment]
I have same issue running on Linux; all I could find is this thread:
https://groups.google.com/forum/#!topic/treefrogframework/dHS2TIDt4JQ
they said they fixed it setting required paths; but did not say what they are.

I added -I/usr/include/treefrog to the make file in the all the folder to fix this error.

**Comment by rafiqueud** [comment]
I have same issue when running treefrog in a Docker.
The following linux command solve the problem to me:

`ln -s /usr/include /usr/local`

That sounds like the make comand of the framework are looking for files in the **/usr/local/include** and some systems the file right path is the **/usr/include**
