### ISSUE TITLE
QByteArray fields of model object read and/or written as hex on SQLite

### ISSUE THREAD

**Issue by bluebear94** [treefrogframework/treefrog-framework#205]
For instance, if you defined the following table in SQLite:

```
CREATE TABLE IF NOT EXISTS User (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(128) UNIQUE,
	passhash BLOB,
	salt BLOB,
	regist INTEGER
);
```

then storing an object to the database would store is `passhash` and `salt` fields as strings instead of blobs.

TreeFrog version: 1.22.0
Qt version: 5.9.5

**Comment by treefrogframework** [comment]
In the current version, the QByteArray type is set to the BLOB type of SQL.
