### ISSUE TITLE
Binding values does not work properly with SQLite

### ISSUE THREAD

**Issue by bluebear94** [treefrogframework/treefrog-framework#206]
TreeFrog version: 1.22.0
Qt version: 5.9.5
SQLite version: 3.22.0

To reproduce:

```
static const char* ewordQuery = R"*(
SELECT Entry.* FROM Entry
    WHERE body LIKE ?
)*";

TSqlQueryORMapper<EntryObject> query;
query.prepare(ewordQuery);
query.addBind("%test%");
query.exec();
```

Expected: `SELECT Entry.* FROM Entry WHERE body LIKE "%test%"` is executed
Actual: `SELECT Entry.* FROM Entry WHERE body LIKE ?` is executed

**Comment by bluebear94** [comment]
Nope, the query just shows incorrectly in the log. The actual query is executed properly.

**Comment by shriramters** [comment]
@treefrogframework is there anyway you can fix the logs? this is still the case today

**Comment by treefrogframework** [comment]
@shriramters 
Used QSqlQuery::executedQuery() for query logging.
It's the spec of Qt.

**Comment by treefrogframework** [comment]
However, QSqlQuery::boundValues() can be used to output additional information.
