### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#210]
Are there any plans to support HTTPS ? If no, can we know at least, how hard it would be to implement this feature? I see that you suggest to use nginx or Apache as reverse proxy server for SSL, caching etc. This is fine for medium and large websites, but not good for small ones that need only HTTPS.
Thanks.

**Comment by aoym** [comment]
No. 
Problem is that I don't understand SSL mechanism well.
I think that using nginx or apache is not difficult.
See http://www.treefrogframework.org/en/user-guide/cooperation-with-the-reverse-proxy-server/

**Comment by amiart** [comment]
Couldn't the HTTPS support be added by rewriting the THttpSocket and TWebSocket classes to inherit from QSslSocket ?
