### ISSUE TITLE
selectTag doesnt work as expected

### ISSUE THREAD

**Issue by quarkme84** [treefrogframework/treefrog-framework#217]
I'm having problems with dynamically creating options with the  select tag.
If one has this in an .erb file:
`<p>
    <% tfetch(QList<Account>, usersList); %>
    <%== selectTag("eventCategory[ownerId]", usersList.size()) %>
    <% for(const auto& i : usersList) { %>
    <%== optionTag(i.username(), i.id(), curUser.id()==i.id()) %>
    <% } %>
    <%== endTag() %>
</p>`

The View generates a closing tag </select> BEFORE any options. I searched the source and I think I found the problem:

in [tviewhelper.cxx:302:](treefrog-framework/src/tviewhelper.cpp)
 `   return tag("select", attr, QString());`

should be the another version  of tag without content (because current one adds automatically an end tag):
 `   return tag("select", attr);`

also selecttag should change the constness.

for me this modification works as expected.

**Comment by treefrogframework** [comment]
Committed in df5ff295165548b9410db549a5dc3efe0aab99d2.
Thanks!
