### ISSUE TITLE
Tutorial problem

### ISSUE THREAD

**Issue by perpeer** [treefrogframework/treefrog-framework#218]
Hi,

I'm trying to run treefrogfreamwork blogapp tutorial, but it's not working. I'm getting this error.

<img width="835" alt="screen shot 2018-09-23 at 18 08 37" src="https://user-images.githubusercontent.com/6865708/45929550-09f8d900-bf5c-11e8-9a8b-121c32fe71de.png">

<img width="936" alt="screen shot 2018-09-23 at 18 11 14" src="https://user-images.githubusercontent.com/6865708/45929555-154c0480-bf5c-11e8-99b2-d3375f217b58.png">

I installed QT 5.10 version
I added qmake path to /etc/paths
My macOS version is Mojave 10.14 and installed Xcode and command line tools

**Comment by code-andres** [comment]
Check your QT installation, looks like your are using two different locations.

One is located in `/usr/local/opt/qt/lib`, the other is in `/Users/ekremtaskiran`

**Comment by treefrogframework** [comment]
Try brew.
 $ brew install mysql-connector-c
 $ brew install --with-mysql --with-postgresql treefrog
