### ISSUE TITLE
error in configure file prevents tools from being built.

### ISSUE THREAD

**Issue by Light-Wizzard** [treefrogframework/treefrog-framework#219]
around line 142 there is a replace that has line wrap after -ltreefroh
replace "... -ltreefrog
|" defaults/appbase.pri
also found on the next line requiring same fix; this causes a make error -ltreefrog
removing the line wrap fixes the error.
replace "... -ltreefrog|" defaults/appbase.pri

Also the file permission do not get set right.

I noticed that Arch Linux Manjaro, does not have the tools, so I could not use the app; I think this is why.

**Comment by treefrogframework** [comment]
Check a docker file.
https://github.com/treefrogframework/treefrog-framework/blob/docker/dockerfiles/Dockerfile
