### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: qml

### ISSUE THREAD

**Issue by mostcute** [treefrogframework/treefrog-framework#221]
when i run ./configure it reports

Project ERROR: Unknown module(s) in QT: qml
Reading /home/cici/work/treefrog-framework-1.22.0/tools/tfmanager/tfmanager.pro
Reading /home/cici/work/treefrog-framework-1.22.0/tools/tfserver/tfserver.pro
Project ERROR: Unknown module(s) in QT: qml
make: *** No rule to make target 'qmake'.  Stop.

Compiling MongoDB driver library ... OK

First, run "make" and "sudo make install" in src directory.
Next, run "make" and "sudo make install" in tools directory.

**Comment by treefrogframework** [comment]
Install qml module.
