### ISSUE TITLE
Can I use raw tcp in this framework?

### ISSUE THREAD

**Issue by grants** [treefrogframework/treefrog-framework#222]
I know websockets has been implemented, but sometimes raw sockets (tcp or udp protocol) is more suitable. Can I get raw tcp packages and keep tcp connections alive using treefrog framework? I know this is more than a web framework, but I just want to ask. Thx.

**Comment by treefrogframework** [comment]
No, you cannot.
Such implementation is needed to do it.

**Comment by grants** [comment]
I see.  Do you have a plan to implement it ?

**Comment by treefrogframework** [comment]
Implemented experimental code in f73760f.
