### ISSUE TITLE
Missing TMultipartFormData::uploadedFile() function

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#235]
The uploadedFile() function described on this page:

http://www.treefrogframework.org/en/user-guide/helper-reference/file-upload.html

no longer exists in TMultipartFormData class.

Also there is no const overload of THttpRequest::multipartFormData() method:

`const TMultipartFormData &multipartFormData() const { return d->multipartFormData; }`

**Comment by treefrogframework** [comment]
Check out 9a4eeaff941b57af170b38e532d6f410a6fb6d72.
Updated docs 47f0a1071dc87ef2a642ca9a251dc6be0a3b6039.
Thanks.

**Comment by amiart** [comment]
Hi, there is one more occurrence of uploadFile() in user-guide/helper-reference/file-upload.md.
Can you also add const overload of multipartFormData() method ?
Thanks.
