### ISSUE TITLE
TSqlQuery::value(int) hides QSqlQuery::value(QString) overload

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#236]
I want to get field value by name, but this doesn't work.

```
TSqlQuery query;
query.exec("SELECT * FROM table");
while (query.next()) {
    int id = query.value(QStringLiteral("id")).toInt();     // build error 
}
```

If I change it to this, it works:

`int id = query.QSqlQuery::value(QStringLiteral("id")).toInt();`

**Comment by treefrogframework** [comment]
Check out 8f4162769ffc050bb88d7d2178ad3b5cc71d9b5f.
Thanks.
