### ISSUE TITLE
Server crash when request body is bigger than LimitRequestBody

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#237]
The server crashes if I set LimitRequestBody=1000000 in application.ini, and upload file bigger than 1MB.
It looks like it it caused by ClientErrorException(413) thrown in THttpSocket::readRequest() but not handled anywhere.

**Comment by aoym** [comment]
Yes.
Process-down is a bug.
Fixed in 3a95c1d.

**Comment by amiart** [comment]
The fix works, thanks.
