### ISSUE TITLE
configure with --enable-mongo not available in macOS

### ISSUE THREAD

**Issue by rafiqueud** [treefrogframework/treefrog-framework#239]
Following the guide:
http://www.treefrogframework.org/en/user-guide/model/access-mongodb.html

The --enable-mongo option its not available in treefrog in the macOS Mojave.
I'm using the 1.23.0 version of treefrog.

I used the --enable-shared-mongoc option instead, but after changing the .ini files to set the database to my localhost the command tspawn --show-collections in my project folder show me the error:

> DatabaseName: databaseName
> HostName:     localhost
> MongoDB opened successfully
> Segmentation fault: 11

How can I find more informations about the error?

**Comment by rafiqueud** [comment]
The application itself can connect to the mongo server, maybe this issue can be closed after changing the guide text in the site for new people that want to use mongo and treefrog with a macOS environment.

Thanks.

**Comment by rafiqueud** [comment]
To make the make command works after using the  ./configure --enable-shared-mongoc.
I needed to copy all the .h files of bson and mongoc that was in the 3rdparty folder to the treefrog/src

Maybe this can be solved.

**Comment by treefrogframework** [comment]
The doc is old.. Could you update it?
  docs/en//user-guide

**Comment by rafiqueud** [comment]
I can update, insert and remove registeres using the TMongoQuery, but no one of find options works.
An EXC_BAD_ACCESS happens.

**Comment by rafiqueud** [comment]
Can you tell me anything to try?
THanks

**Comment by rafiqueud** [comment]
In Resume:
The situation is:
tspawn --show-collections = Segmentation fault: 11
_______________________________________________________________
In the TMongoQuery update/create/save works, but the find option causes an EXC_BAD_ACCESS

**Comment by rafiqueud** [comment]
Using the --enable-shared-mongoc do not works right. 
Maybe the frameworks its prepared to use only the mongoc driver included, news versions of mongoc could have some breaking changes.

Thanks for the help.

**Comment by treefrogframework** [comment]
Fixed in 2197c6e96d84a34688f42e384e365992a7e27eff.
Try please.

Run in advance.
 $ brew install mongo-c-driver
 $ brew link mongo-c-driver
