### ISSUE TITLE
TMultipartFormData::originalFileName() gives full path without backslashes for IE and Edge

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#240]
I use the following form to upload files:

```
<form action="" method="POST" enctype="multipart/form-data">
     <label>File:</label><input name="file" type="file"/>
     <label>Description:</label><input name="description" type="text"/>
     <input type="submit" value="Upload file"/>
</form>

```
server side code:

```
const TMultipartFormData &formData = request.multipartFormData();
QString origname = formData.originalFileName("file");
```

If I upload a file called photo.jpg from Firefox or Chrome then the origname is:

`photo.jpg`

but when I upload the file using IE or Edge the origname is:

`C:UsersAdministratorDesktopphoto.jpg`

I would like to extract only filename from the path using QFileInfo::fileName(), but the path is missing slashes.

**Comment by treefrogframework** [comment]
I tried the code, but I could not reproduce that.
Using Inspector tool of a browser, you could check the HTTP request message of IE or Edge.
Could you paste the request message here?

**Comment by amiart** [comment]
Here is request headers for Internet Explorer 11:

```
POST /file/upload HTTP/1.1
Accept: text/html, application/xhtml+xml, image/jxr, */*
Host: localhost:8800
Content-Length: 12290
Connection: Keep-Alive
Cache-Control: no-cache
Referer: http://localhost:8800/test/index.html
Accept-Language: pl-PL
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
Content-Type: multipart/form-data; boundary=---------------------------7e365b411444
Accept-Encoding: gzip, deflate
DNT: 1
Cookie: session_id=77900c90be46c640b28052c5b878127036ddbb0b

-----------------------------7e365b411444
Content-Disposition: form-data; name="file"; filename="C:\Users\Administrator\Desktop\photo.png"
Content-Type: image/png

PNG
...

```

I guess the problem is `TMimeHeader::parseHeaderParameter(const QByteArray &header) `function.

**Comment by treefrogframework** [comment]
Fiexed in 69350949fc103668dd88507c8c557d39a3505add.
Thanks.

**Comment by amiart** [comment]
The fix works both on IE and Edge.
Thank you.
