### ISSUE TITLE
Incorrent Content-Type returned for files with uppercase extension

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#242]
TreeFrog should return `Content-Type: image/png` header both for image.png and image.PNG.
Currently it returns `Content-Type: text/plain; charset=UTF-8` for the second one.

**Comment by treefrogframework** [comment]
Fixed in 23781a539e278694b04ec8d4a432f6de4e266462.
Check out.

**Comment by amiart** [comment]
Thanks!
