### ISSUE TITLE
Set domain in session TCookie

### ISSUE THREAD

**Issue by proostas** [treefrogframework/treefrog-framework#245]
Hello everyone. 

I've come across a situation when I need to set a domain for a session cookie. Is it currently possible? Maybe add it as an option in the application.ini?

**Comment by treefrogframework** [comment]
Set this in application.ini. It's a default value.

Session.StoreType=cookie

**Comment by proostas** [comment]
Probably I need to clarify the situation. I need to set the domain for the session cookie like '.domain.net' (with leading dot) for this cookie to be valid for all subdomains (e.g. static.domain.net, app.domain.net, www.domain.net, etc). Otherwise, Treefrog creates a new cookie for each subdomain and I loose track of a particular client.

TCookie is a typedef of QNetworkCookie which has a method .setDomain(), which I need to set for the session cookie to '.domain.net' to overcome the subdomain problem. The current implementation of Treefrog puts QString() for the domain, but it would be a good idea to make it configurable. 

That is, a Session.Domain option in application.ini would solve the situation.

I need this because I want to protect some files in static.domain.net and use Nginx'es internall authorization redirects, but the problem is that browser do not send the session cookie for this subdomain, because it is accociated with app.domain.net.

**Comment by treefrogframework** [comment]
Implemented in ffbc98bbdaa3883319fcb241aa7cb846fcd685aa. Try it.
Add  the following param in application.ini.
```
  Session.CookieDomain=your_domain
```

Thanks!

**Comment by proostas** [comment]
Everything's working great now. Thank you very much!
