### ISSUE TITLE
SessionCookieDomain

### ISSUE THREAD

**Issue by Mohibur** [treefrogframework/treefrog-framework#246]
Hi, 
Not an issue. 
I have downloaded 1.24.0. I was looking for anything related to session cookie domain. I did not find any in the source code. Then I noticed in master branch there is new variable as **SessionCookieDomain**. Is there any chance that you are going to update your downloadable? Or shall I just compile master branch?

Best Regards,
Johny

**Comment by treefrogframework** [comment]
Use the master branch until a next version is released.

**Comment by treefrogframework** [comment]
Use new variable in v1.25.0 or later.
 Session.CookieDomain=...
