### ISSUE TITLE
can't compile on windows

### ISSUE THREAD

**Issue by silentmissile** [treefrogframework/treefrog-framework#258]
my platform is:
MSVC community 2017 x64
Qt-5.13.0 x64 msvc2017, it's installed from official package not compiled by my computer

the source of treefrog is 1.25.0

the compile command is:

call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
call "C:\Qt\5.13.0\msvc2017_64\bin\qtenv2.bat"
configure

then the error message is

-- SSL disabled
-- SASL disabled
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: F:/Source/treefrog-framework-1.25.0/3rdparty/mongo-driver
Compiling MongoDB driver library ...
Compiling LZ4 library ...
Build failed.
LZ4 not available.

then compiling process stops

can you give me some advise?

**Comment by treefrogframework** [comment]
Try the following command in '3rdparty' directory.
 > devenv lz4\visual\VS2017\lz4.sln /project liblz4 /rebuild "Release|win32" 

Let me show error.

**Comment by silentmissile** [comment]
the error message is:

error MSB8036: can't find Windows SDK version 8.1

I didn't install Windows SDK version 8.1 in my MSVC2017, so the error message is very clear

then I edit the sln file by VS, change the SDK version from 8.1 to 10, then compile passes
