### ISSUE TITLE
Calling stored procedure from model

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [treefrogframework/treefrog-framework#259]
I would like to call a stored procedure in the database from within a model with a result set identical to what is returned by the table. Would you please give me some guidance on best practice for doing this in the TreeFrog ORM? Thank you.

**Comment by treefrogframework** [comment]
You can add a query function for the stored procedure and modify update() or save() method so as to call the function.
```
class T_MODEL_EXPORT Blog : public TAbstractModel
{
public:
   :
    bool update() override { return TAbstractModel::update(); }
    bool save()   override { return TAbstractModel::save(); }
```

**Comment by gi9obru0etuPlc6wozls** [comment]
My apologies, I'm not well versed in Qt5 and the TreeFrog ORM. I am trying to preform the query, but no results are being returned. 
`
        
        QJsonArray TestTree::getJsonTree()
        {
            tDebug("TestTree::getJsonTree 1");
            QJsonArray array;
            TSqlORMapper<TestTreeObject> mapper;
            QSqlQuery qs = mapper.database().exec("select * from test_tree");
            tDebug("TestTree::getJsonTree 2");
        
            for (TSqlORMapperIterator<TestTreeObject> i(mapper); i.hasNext(); ) {
                tDebug("TestTree::getJsonTree 2a");
                array.append(QJsonValue(QJsonObject::fromVariantMap(TestTree(i.next()).toVariantMap())));
            }
        
            tDebug("TestTree::getJsonTree 3");
            return array;
        }
`

**Comment by treefrogframework** [comment]
Use TSqlQuery instead of QSqlQuery.
See here.
http://www.treefrogframework.org/en/user-guide/model/sql-query.html
https://doc.qt.io/qt-5/qsqlquery.html

**Comment by gi9obru0etuPlc6wozls** [comment]
Thank you. This is exactly what I was looking for.
