### ISSUE TITLE
Build problems with mingw32-make on Windows

### ISSUE THREAD

**Issue by fehrlest** [treefrogframework/treefrog-framework#260]
I use the release package 1.25.0 
I execute the command "configure --prefix=D:\TreeFrog\1.25.0" 

the Output in in the attachment

[issue_during_configure_v1.25.0.txt](https://github.com/treefrogframework/treefrog-framework/files/3507195/issue_during_configure_v1.25.0.txt)

**Comment by treefrogframework** [comment]
Now, not supported for MinGW. You could use WSL if compiling in g++ on Windows.
In Windows, supports for MSVC only.
