### ISSUE TITLE
replace QDir::separator() by "/"

### ISSUE THREAD

**Issue by DRFrederik** [treefrogframework/treefrog-framework#264]
Not a bug but a request for a "nice to have" improvement:
Treefrog uses QDir::separator() to build file paths.

https://doc.qt.io/qt-5.12/qdir.html#separator
You do not need to use this function to build file paths. If you always use "/", Qt will translate your paths to conform to the underlying operating system.
...

When replacing every instance of QDir::separator() in the source by "/", "Tadpole --debug" seems to work fine.
Using QDir::separator() is confusing when printing a file path of viewing a path string in the debugger on Windows. In order to discourage its further use it should be replaced by "/".

**Comment by treefrogframework** [comment]
Could you let me show the pull-request.

**Comment by treefrogframework** [comment]
Merged.
