### ISSUE TITLE
JSON data

### ISSUE THREAD

**Issue by qlcorp** [treefrogframework/treefrog-framework#266]
Postgres support a JSON data type. Ideally, what I would like to do is have the ORM store this in a QJsonDocument, or a class that is derived from a QJsonDocument

How can this be accomplished?

**Comment by treefrogframework** [comment]
The ORM wraps QSqlQuery class.
If QSqlQuery supports for JSON data, the ORM could support for it.

In a model class, you can convert the data stored as TEXT type, not in ORM.
The implementation is needed in the model.

**Comment by qlcorp** [comment]
Thank you.
