### ISSUE TITLE
User-defined type on ORM

### ISSUE THREAD

**Issue by jorbs** [treefrogframework/treefrog-framework#267]
I am trying to use a custom class that wraps a `QString` so that it receives the value stored on a PostgreSQL `varchar` column. The string in my class instance is always empty, although it has a defined value in the database. Is it possible to use custom types in the ORM, instead of QString and so on?

**Comment by treefrogframework** [comment]
The ORM wraps QSqlQuery class, so you cannot receives by custom class without changing ORM implementation.
You could convert the data in model class, not in ORM class.
