### ISSUE TITLE
SQL database driver download page 404

### ISSUE THREAD

**Issue by Flone-dnb** [treefrogframework/treefrog-framework#270]
I've downloaded the binary .exe of the TreeFrog and currently going through the tutorial. Getting the QSqlDatabase: QMYSQL driver not loaded error but can't download driver because "If you receive this message, download the SQL database driver from the download page, and install it" download page is 404.

Tried a lot of solutions on the internet about QSqlDatabase: QMYSQL driver not loaded problem, spend about 3 hours and no result.

P.S. I've also tried building QMYSQL driver from Qt sources but got a lot of errors and tried a lot of things which did nothing.

**Comment by treefrogframework** [comment]
Whit's is your environment?

In Linux, you can get them by apt-get command. 
See http://www.treefrogframework.org/en/user-guide/install/

In Windows, install by the TreeFrog installer for Windows because the installer includes the drivers.
See http://www.treefrogframework.org/en/download/

In Mac, you can them get by brew command.

**Comment by Flone-dnb** [comment]
> Whit's is your environment?
> 
> In Linux, you can get them by apt-get command.
> See http://www.treefrogframework.org/en/user-guide/install/
> 
> In Windows, install by the TreeFrog installer for Windows because the installer includes the drivers.
> See http://www.treefrogframework.org/en/download/
> 
> In Mac, you can them get by brew command.

I've used TreeFrog installer for Windows but somehow I don't have mysql plugin (QMYSQL).

**Comment by treefrogframework** [comment]
QMYSQL plugin for Windows not found.
```
> tspawn --show-drivers
Available database drivers for Qt:
  QSQLITE
  QODBC
  QODBC3
  QPSQL
  QPSQL7

> tspawn --show-driver-path
C:/Qt/5.12.4/msvc2017_64/plugins/sqldrivers

> cd c:\Qt\5.12.4\msvc2017_64\plugins\sqldrivers
> dir
 :
2019/06/24  23:00    <DIR>          .
2019/06/24  23:00    <DIR>          ..
2019/06/13  12:49         1,169,528 qsqlite.dll
2019/06/13  12:49         1,824,888 qsqlited.dll
2019/06/13  12:49            94,328 qsqlodbc.dll
2019/06/13  12:49           216,696 qsqlodbcd.dll
2019/06/13  12:49            76,920 qsqlpsql.dll
2019/06/13  12:49           183,928 qsqlpsqld.dll
 :
```

The driver plugin must be built by yourself.
https://forum.qt.io/topic/100048/error-qmysql-plugin-on-windows
