### ISSUE TITLE
how to create TCP server in treefrog application

### ISSUE THREAD

**Issue by FineBlack** [treefrogframework/treefrog-framework#273]
I want to integrate TCP server in treefrog application，What should I do? 
Because I want to integrate TCP server and web server in an treefrog application, running on arm linux, and some sensor devices can connect to the TCP server, and the corresponding sensor values are displayed on the web page. It's like an edge gateway.
Thank.

**Comment by FineBlack** [comment]
Thank you for your reply. Sometimes the sensor device does not support mqtt protocol and supports pure TCP protocol, which makes us feel troublesome and Uncomfortable. Therefore I want to integrate my simple pure TCP server written C++ into the beautiful treefrog application with a new thread，and, and I can't find the main function of treefrog application. Can I continue to think about this? Can you give me some advice? Sorry. Maybe I'm a little wordy.
Thank you for reading my words in the busy schedule.

**Comment by FineBlack** [comment]
> You could build TreeFrog as a REST server and the sensor devices could post json data. Also use WebSocket protocol and CBOR data format.
> Currently, it is not possible to use the application server as a pure TCP server without implementation.

Thank you for your reply. Sometimes the sensor device does not support mqtt protocol and supports pure TCP protocol, which makes us feel troublesome and Uncomfortable. Therefore I want to integrate my simple pure TCP server written C++ into the beautiful treefrog application with a new thread，and, and I can't find the main function of treefrog application. Can I continue to think about this? Can you give me some advice? Sorry. Maybe I'm a little wordy.
Thank you for reading my words in the busy schedule.

**Comment by treefrogframework** [comment]
It's a instance of TThreadApplicationServer class to accept a incoming socket.
See TThreadApplicationServer::run() function in Linux.
You could modify the implementation as you wish.
