### ISSUE TITLE
Docker run failes with INI file not found [/webapp/config/application.ini]

### ISSUE THREAD

**Issue by camccar** [treefrogframework/treefrog-framework#281]
# Running the official Docker container fails.

## The error:

`INI file not found [/webapp/config/application.ini]`

### Steps to reproduce
1. `docker pull treefrogframework/treefrog`
2. `docker run -p 8800:8800 treefrogframework/treefrog`

See the error

`INI file not found [/webapp/config/application.ini]`

**Comment by treefrogframework** [comment]
That container is for AP server of treefrog.
See the Dockerfile, https://hub.docker.com/r/treefrogframework/treefrog/dockerfile

You can use run it after mounting a volume of a treefrog app.
Also can change the last command.
