### ISSUE TITLE
Boolean fields not initalized in model class

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#282]
SQL models generated with the tspawn command do not have initialized boolean fields, and integer fields are initialized twice. See atached screenshot.

![modelgenerator_bug](https://user-images.githubusercontent.com/9396016/74334069-7961a980-4d99-11ea-84f2-3d7726d4900e.png)

**Comment by amiart** [comment]
And the setter for boolean properties in SQL model takes **const bool &** parameter instead of **bool**:
```
bool isActive() const;
void setIsActive(const bool &isActive);
```

**Comment by amiart** [comment]
Note, if the model class has a an explicitly declared destructor, copy constructor or assignment operator, then the compiler does not generate a move constructor and move assignment operator for such a class. This means that the model class cannot be moved. See diagram here:

https://stackoverflow.com/questions/4943958/conditions-for-automatic-generation-of-default-copy-move-ctor-and-copy-move-assi

The solution is to remove from model destructor, copy constructor, and assingment operator or declare explicitly move constructor and move assignment operator.

**Comment by amiart** [comment]
No need to use new in copy constructor, since QSharedDataPointer::operator->() automatically call detach() if the shared data object's reference count is greater than 1.

**Comment by treefrogframework** [comment]
Thanks.
Modified to initialize bool fields.
Stopped to create the code initializing parameters in model class.

committed in b08606df30715f821f18a486a9a2614d7aa69f6d.

**Comment by amiart** [comment]
I see you fixed const bool& parameters too.
Now it works great, thanks !
