### ISSUE TITLE
Build without mongo support

### ISSUE THREAD

**Issue by TyrasNistru** [treefrogframework/treefrog-framework#287]
Is there a way to build the framework without the blunded mongo support?

My application has its own way to access the mongo database, through a 3rd-party library which links statically to its own version of libmongoc. But the version blunded with treefrog conflicts with it.

**Comment by treefrogframework** [comment]
@TyrasNistru 
You could edit  the mongodb section of src/core.pro file  (below line 385) for TreeFrog to link with your lib.

**Comment by TyrasNistru** [comment]
I ended up messing a little with the Makefile generated in the src folder to point to my library and it worked. Thanks!
