### ISSUE TITLE
Cookie lost when redirect

### ISSUE THREAD

**Issue by grants** [treefrogframework/treefrog-framework#288]
I did a redirect in my controller class like this:
redirect(urla("myaction"));
And I found that the page header cookie was lost, could you tell me how to fix this or did I do it wrong?

**Comment by treefrogframework** [comment]
It's a bug that occur when set max-age of a cookie to 0.
Set a positive value to max-age in application.ini to avoid the bug.

Or, try this commit, 8ca13295ae7d49336707615c283f934ac8cde381.

**Comment by grants** [comment]
It worked. Thx.
