### ISSUE TITLE
windows,qt5.12.8.treefrog1.28.0,use mingw32-make. but cmd print "MSVC Compiler not found"

### ISSUE THREAD

**Issue by jsxyhyj** [treefrogframework/treefrog-framework#289]
cmd Qt 5.12.8 (MinGW 7.3.0 32-bit)
E:\sources\treefrog-framework-1.28.0>configure --enable-debug
MSVC Compiler not found

你好，windows下使用qt5.12.8的mingw32-make编译，应该不需要MSVC Compiler。现在配置时就打印 "MSVC Compiler not found"
请问怎么解决？谢谢

**Comment by treefrogframework** [comment]
The site documentation was out of date.
TreeFrog no longer supports MinGW.
Please use Visual Studio in Windows.
