### ISSUE TITLE
TSmtpMailer: Prevent STRIPTLS attacks

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#290]
The STARTTLS in TSmtpMailer class is vulnerable to STRIPTLS attacks.

According to Wikipedia:
https://en.wikipedia.org/wiki/Opportunistic_TLS

> Because the initial handshake takes place in plain text, an attacker in control of the network can modify the server messages via a man-in-the-middle attack to make it appear that TLS is unavailable (called a STRIPTLS attack). Most SMTP clients will then send the email and possibly passwords in plain text, often with no notification to the user.
...
STRIPTLS attacks can be blocked by configuring SMTP clients to require TLS for outgoing connections (for example, the Exim Message transfer agent can require TLS via the directive "hosts_require_tls")

The solution is to add a new parameter in application.ini:

ActionMailer.smtp.EnableSTARTTLS=true
ActionMailer.smtp.RequireTLS=true      #  <-- new parameter (default false)

arnd then check it in tsmtpmailer.cpp before line 170:

```
if (requireTls && !tlsEnable) {
     tSystemError("STARTTLS not enabled");
     cmdQuit();
     return false;
}

if (requireTls && !tlsAvailable) {
    tSystemError("The mail server does not support TLS");
    cmdQuit();
    return false;
}

if (tlsEnable && tlsAvailable) {
    if (!cmdStartTls()) {
        cmdQuit();
        return false;
    }
}
```

**Comment by treefrogframework** [comment]
Deleted the EnableSTARTTLS parameter and added a RequireTLS parameter.
It will prevent STRIPTLS attacks. 
0370b7d54ec7ea66a57ffa93acfbe41b86402f8f

**Comment by amiart** [comment]
Hi, your patch look good, but does it mean that the #299 will not be merged ?
It has some advantages:
- adds support for true SSL connections
- doesn't deprecate EnableSTARTTLS parameter
- logs SSL errors (certificate expiration etc.)
- updates examples in documentation

**Comment by treefrogframework** [comment]
Unfortunately, it conflicted with your patch.
Today, we can think The EnableSSL parameter is always TRUE.
Could you update the docs?

**Comment by amiart** [comment]
Can you reconsider applying the patch #299 ?
I've uploaded a new version that reverts 0370b7d54ec7ea66a57ffa93acfbe41b86402f8f  and adds EnableSSL parameter.
Thanks.

**Comment by treefrogframework** [comment]
I think the RequireTLS parameter is enough.
Because the EnableSSL parameter is always TRUE, not needed it.

**Comment by amiart** [comment]
OK, then. But please update the docs so everyone will know that the parameter EnableSSL is now called RequireTLS
and log SSL certificate errors in TSmtpMailer::cmdStartTls() - the certificate may not be trusted or could expire.

```
bool TSmtpMailer::cmdStartTls() 
{
    // ...

    socket->startClientEncryption();
    if (!socket->waitForEncrypted(5000)) {
        tSystemError("SMTP STARTTLS negotiation timeout: %s", qPrintable(socket->errorString()));
        for (const auto &err : socket->sslErrors()) {
            tSystemError("SMTP SSL error %d: %s", int(err.error()), qPrintable(err.errorString()));
        }
        return false;
    }

    // ...
}
```

**Comment by treefrogframework** [comment]
Looks like good!
Commited in 48c6da9f1d27c7627d4f6f4c9d916ff48bb60aea.

**Comment by amiart** [comment]
Thank you.
