### ISSUE TITLE
Project build error when treefrog installed in non-standard location

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#292]
Hi,
I installed treefrog framework in non-standard location using --prefix parameter.

> ./configure --enable-debug --prefix=/opt/treefrog/1.29.0-Qt_5_9_7-gcc48-debug

But when I build my project I get many errors, because the appbase.pri has hardcoded include and lib paths for unix:

> unix:LIBS += -Wl,-rpath,. -Wl,-rpath,/usr/lib -L/usr/lib -ltreefrog
> unix:INCLUDEPATH += /usr/include/treefrog

I think for unix, just like for Windows, the path should be taken from the TFDIR environment variable, and if such a variable does not exist, it should take the default path.

Config:
Ubuntu 14.04 x64
Qt 5.9.7
Treefrog 1.29.0

**Comment by amiart** [comment]
This happens for project created on Windows, and then built on unix-like system.

**Comment by treefrogframework** [comment]
A build config generated in Windows can not reuse in UNIX-like system.
Run the configure script in each system.

**Comment by amiart** [comment]
Yes, I did it.  But the problem is that the TreeFrog configure script replaces install paths in <treefrog_prefix_path>/defaults/appbase.pri file, but not in my project's appbase.pri.
So If I create a project on Windows and then copy it to Ubuntu, then the paths will be wrong.

**Comment by treefrogframework** [comment]
I don't understand your problem.
Re-run the configure script in your Ubuntu.

**Comment by amiart** [comment]
1. Install treefrog on Windows
2. Create blogapp project on Windows
3. Install treefrog on Ubuntu in non-standard location using --prefix parameter.
4. Copy blogapp project from Windows to Ubuntu
5. Build the project on Ubuntu using QtCreator and setup described here:
https://www.treefrogframework.org/en/user-guide/debug/

In file included from applicationhelper.cpp:1:0:
applicationhelper.h:4:19: fatal error: TGlobal: No such file or directory
 #include <TGlobal>
                   ^
compilation terminated.

**Comment by amiart** [comment]
I fixed this by manually changing the paths in my project's appbase.pri file.
