### ISSUE TITLE
Precompiled headers breaks centos compilation

### ISSUE THREAD

**Issue by Grennith** [treefrogframework/treefrog-framework#298]
Hi,
it appears the precompiled headers merge broke oob compilation on CentOS 8

./configure runs through just fine, compilation on the other hand stops
`cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: .obj/treefrog: No such file or directory
compilation terminated.
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: .obj/treefrog: No such file or directory
compilation terminated.
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: .obj/treefrog: No such file or directory
`
Reverted to c03c95cd258166f5136f0ce945ad97706a4d617d, compilation runs through nicely.

**Comment by amiart** [comment]
Please try pull request #297, and then clean your build directory:

```
./configure
cd src
make distclean
make
cd ../tools
make distclean
make
```

**Comment by treefrogframework** [comment]
#297 merged.
