### ISSUE TITLE
Could I use tf framework in a commercial project?

### ISSUE THREAD

**Issue by grants** [treefrogframework/treefrog-framework#302]
I know that this is not a question about framework itself, but this repo is a place I can reach right now.

I want to introduce treefrog to my company and use it in our future commercial project where it will be needed. Could I use it free in a commercial project or product or should I pay a license fee to use it ?  Any suggestions is grateful. Thx.

**Comment by treefrogframework** [comment]
It's the New BSD license. Free for commercial use.
https://github.com/treefrogframework/treefrog-framework/blob/master/copyright

**Comment by grants** [comment]
Thank you.

**Comment by jokey35** [comment]
What about the linked QT libraries? QT seems to be free only if you share the source code. TF uses QT functions, so should I have a QT license during the development?
