### ISSUE TITLE
Basic tutorial

### ISSUE THREAD

**Issue by mbnoimi** [treefrogframework/treefrog-framework#306]
Hi,

I'm still a newbie and I want to know from where can I start for creating a very basic RESTful service.
The mentioned tutorial using MVC expensively (blog demo) while I don't care about MVC at this stage. I just want a very basic tutorial within a single file.

May you please give me nudge as a kick start.

Look at [drogon](https://github.com/an-tao/drogon) tutorial it's very basic and easy to understand.

```C++
#include <drogon/drogon.h>
using namespace drogon;
int main()
{
    app.registerHandler("/test?username={name}",
                    [](const HttpRequestPtr& req,
                       std::function<void (const HttpResponsePtr &)> &&callback,
                       const std::string &name)
                    {
                        Json::Value json;
                        json["result"]="ok";
                        json["message"]=std::string("hello,")+name;
                        auto resp=HttpResponse::newHttpJsonResponse(json);
                        callback(resp);
                    },
                    {Get,"LoginFilter"});
    app().setLogPath("./")
         .setLogLevel(trantor::Logger::kWarn)
         .addListener("0.0.0.0", 80)
         .setThreadNum(16)
         .enableRunAsDaemon()
         .run();
}
```

**Comment by treefrogframework** [comment]
For small web apps, using the drogon framework is a good choice.

If you use TreeFrog framework, you could implement RESTful service without views, for example, using renderJson() function.

Refer API Reference too, http://api-reference.treefrogframework.org/annotated.html

**Comment by mbnoimi** [comment]
Thanks for the reply but the link pointed to doesn't explain anything to me!
It's just an annotation which doesn't answer my question at all. I looked into it for some hours and ended to a dead end.
The available documentation is really poor and don't help to start using TreeFrog.

Within one hour I could create a basic REST apps using drogon, Cutelyst, Wt and pistache while I couldn't do anything with TreeFrog because lack of examples.
