### ISSUE TITLE
How to render an image to <img> tag?

### ISSUE THREAD

**Issue by grants** [treefrogframework/treefrog-framework#309]
I had an img tag in my .erb template file, like this:

```
<body>
    <img src="/mycontroller/myaction" />
</body>
```

This tag's src attribute was my action url, this action aimed to generate an image by QImage and QPainter class methods, its content was dynamic. 

I only learned to use "render" or "renderText" in my action, so how can I show this dynamic generated image data to my view tag?  

Thanks.

**Comment by amiart** [comment]
You can use sendData() or sendFile() function in your controller.

```
QByteArray image;
// generate image
sendData(image, "image/png");
```
```
sendFile("file_path", "image/png");
```

**Comment by grants** [comment]
My action codes showed below:
```
QImage image(100, 50, QImage::Format_ARGB32_Premultiplied);
QPainter painter(&image);
painter.fillRect(image.rect(), Qt::yellow);
painter.drawText(image.rect(), Qt::AlignCenter | Qt::AlignVCenter, "hello, world");
QByteArray outputImageData;
QBuffer buffer(&outputImageData);
buffer.open(QIODevice::WriteOnly);
image.save(&buffer, "PNG");
sendData(outputImageData, "image/png");
```
And when I visit in my browser,  it said: "The connection was reset", no image showed up.
What's wrong with this? Thanks.

**Comment by amiart** [comment]
I guess you need to compile treefrog library with -`-enable-gui-mod` parameter.
https://www.treefrogframework.org/en/user-guide/helper-reference/image-manipulation.html

**Comment by grants** [comment]
My tf app run in a Linux server without desktop environment, so I couldn't open this parameter to enable gui mod. When I opened it, compilation progress was broken. I don't know how to compile it without x system, could you tell me a solution or any suggestions? thanks.
