### ISSUE TITLE
Please provide an example of operating redis

### ISSUE THREAD

**Issue by gleke** [treefrogframework/treefrog-framework#315]
Please provide an example of operating redis. Redis requires a password to log in

**Comment by treefrogframework** [comment]
Apologies for no doc.

See https://github.com/treefrogframework/treefrog-framework/issues/66
See http://api-reference.treefrogframework.org/classTRedis.html

**Comment by gleke** [comment]
I can't  find  how  to  connetc  redis  in   TRedis Class Reference

**Comment by gleke** [comment]
Public Member Functions
--
  | TRedis ()
 
  | TRedis (const TRedis &other)
 
virtual | ~TRedis ()
 
bool | isOpen () const

**Comment by treefrogframework** [comment]
The framework automatically connects to the server that has information of config/redis.ini.
Try it.

**Comment by treefrogframework** [comment]
There was a bug of poll condition in redis driver class.
Fixed in cb50dcb63283dff34387e2778c6ca8710f555267
