### ISSUE TITLE
Using GDB with TreeFrog

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [treefrogframework/treefrog-framework#316]
Hello, thank you for a very elegant C++  framework.

I would like to use GDB to help with debugging my controllers and models. Does anyone have any experience with doing this that would lend some guidance? This is as far as I have been able to get:
`
[root@app01 development]# gdb /usr/bin/treefrog 
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-12.el8
...
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/treefrog...done.
(gdb) run --debug -e dev
Starting program: /usr/bin/treefrog --debug -e dev
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-127.el8.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
...
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffef053700 (LWP 139559)]
[Thread 0x7fffef053700 (LWP 139559) exited]
invalid argument
[Inferior 1 (process 139555) exited with code 01]
Missing separate debuginfos, use: yum debuginfo-install glib2-2.56.4-8.el8.x86_64 gmp-6.1.2-10.el8.x86_64 libblkid-2.32.1-24.el8.x86_64 libcap-2.26-4.el8.x86_64 libffi-3.1-22.el8.x86_64 libgcc-8.3.1-5.1.el8.x86_64 libgcrypt-1.8.5-4.el8.x86_64 libgpg-error-1.31-1.el8.x86_64 libicu-60.3-2.el8_1.x86_64 libidn2-2.2.0-1.el8.x86_64 libmount-2.32.1-24.el8.x86_64 libselinux-2.9-4.el8_3.x86_64 libstdc++-8.3.1-5.1.el8.x86_64 libtasn1-4.13-3.el8.x86_64 libunistring-0.9.9-3.el8.x86_64 libuuid-2.32.1-24.el8.x86_64 lz4-libs-1.8.3-2.el8.x86_64 nettle-3.4.1-2.el8.x86_64 openssl-libs-1.1.1g-11.el8.x86_64 p11-kit-0.23.14-5.el8_0.x86_64 pcre2-10.32-2.el8.x86_64 pcre2-utf16-10.32-2.el8.x86_64 qt5-qtbase-5.12.5-6.el8.x86_64 qt5-qtdeclarative-5.12.5-1.el8.x86_64 systemd-libs-239-41.el8_3.x86_64 xz-libs-5.2.4-3.el8.x86_64 zlib-1.2.11-16.el8_2.x86_64`

**Comment by treefrogframework** [comment]
see https://www.treefrogframework.org/en/user-guide/debug/

**Comment by gi9obru0etuPlc6wozls** [comment]
Thank you. This was most helpful. I was able to configure CLion for remote GDB debugging with your kind assistance.
