### ISSUE TITLE
Proposed change to tsqlormapper

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [treefrogframework/treefrog-framework#317]
I propose a refactoring of TSqlORMapper to enable the setting of limits, offsets, and sort order without knowing the specific type of TSqlORMapper. My proposed change involves the addition of a base class and would look

    class TSqlORMapperBase : public virtual QSqlTableModel {
    public:
        void setLimit(int limit);
        void setOffset(int offset);
        void setSortOrder(int column, Tf::SortOrder order = Tf::AscendingOrder);
        void setSortOrder(const QString &column, Tf::SortOrder order = Tf::AscendingOrder);
    };

    template <class T>
    class TSqlORMapper : public TSqlORMapperBase {
    public:
        TSqlORMapper();
        virtual ~TSqlORMapper();
   
Please advise if you agree with this change and I will make a pull request. Thank you.

**Comment by treefrogframework** [comment]
Please tell me how to use the TSqlORMapperBase class.
You could show me sample code.
Thanks.

**Comment by gi9obru0etuPlc6wozls** [comment]
The need to get frequently used GET variables for our RESTful API in TreeFrog such as sort order, filtering, start and limit. We implemented a new helper class we call "RequestCriteria" that helps with getting the variables and translating them into criteria and mapper. Please see the attached

[RequestCriteria_h.pdf](https://github.com/treefrogframework/treefrog-framework/files/5896514/RequestCriteria_h.pdf)
[RequestCriteria_cpp.pdf](https://github.com/treefrogframework/treefrog-framework/files/5896515/RequestCriteria_cpp.pdf)

Changing tsqloramapper.h:

    class TSqlORMapperBase : public virtual QSqlTableModel {
    public:
        virtual void setLimit(int limit) = 0;
        virtual void setOffset(int offset) = 0;
        virtual void setSortOrder(int column, Tf::SortOrder order = Tf::AscendingOrder) = 0;
        virtual void setSortOrder(const QString &column, Tf::SortOrder order = Tf::AscendingOrder) = 0;
        virtual int findCount(const TCriteria &cri = TCriteria()) = 0;
        virtual int findCountBy(int column, const QVariant &value) = 0;
        virtual int find(const TCriteria &cri = TCriteria()) = 0;
        int findBy(int column, QVariant value) {  };
        virtual int findIn(int column, const QVariantList &values) = 0;
    };
    
    template <class T>
    class TSqlORMapper : public virtual TSqlORMapperBase
    {
    public:
        TSqlORMapper();
        virtual ~TSqlORMapper();
    ...



This enables us to have minimal implementations in the controller and model:

    void ProductRestController::get() {
    
        auto *mapper = new TSqlORMapper<ProductObject>;
        auto propertyMap = Product::propertyIndexMap();
    
        try {
            RequestCriteria requestCriteria(propertyMap, mapper);
            auto r = httpRequest();
            requestCriteria.add(r);
            return renderJsonSuccess(Product::findJson(requestCriteria), requestCriteria.getCount());
        }
        catch (std::exception &e) {
            rollbackTransaction();
            this->setStatusCode(Tf::InternalServerError);
            renderJsonFail(e.what());
        }
    }

model:

    QJsonArray Product::findJson(const RequestCriteria &criteria)
    {
        QJsonArray jsonArray;
        auto *mapper = dynamic_cast<TSqlORMapper<ProductObject> *>(criteria.getMapper());
    
        if (mapper->find(criteria.getCriteria()) > 0) {
            for (TSqlORMapperIterator<ProductObject> i(*mapper); i.hasNext(); ) {
                jsonArray.append(Product(i.next()).toJsonObject());
            }
        }
        return jsonArray;
    }

**Comment by treefrogframework** [comment]
Thanks.

Is it like this?
#319

**Comment by gi9obru0etuPlc6wozls** [comment]
Yes, thank you.
