### ISSUE TITLE
Licensing things

### ISSUE THREAD

**Issue by jokey35** [treefrogframework/treefrog-framework#322]
Hi!
According to QT website, QT is a commercial software to buy when you are not willing to publish your source code freely. Does this mean that I need a valid QT license during development, as I do not want to share the code with the customer? Customers will pay for the software created with TreeFrog.
Thank you.

**Comment by proostas** [comment]
As long as you use Qt as shared libraries (.so/.dylib/.dll) and do not link statically, you can keep your code under any kind of license you like. If you link to Qt statically you must use commercial version of Qt to close-source your project (which is still debatable). 

But, anyway, your Treefrog app is a collection of shared libraries so they can be considered as separate apps and you can release you project using any kind of license including closed-sourced.

**Comment by treefrogframework** [comment]
It's correct.
