### ISSUE TITLE
Bool field

### ISSUE THREAD

**Issue by mobilemindtec** [treefrogframework/treefrog-framework#329]
Hi,

I have a mysql database with multiple columns of type tinyint. When I generate mo model via `tspawn model` command these fields are created as char, but they are bool. If in the code I use true or false in this char field, the ORM puts an empty value in the SQL insert. Is there any way to say that the tinyint field is bool?

Thanks!

**Comment by treefrogframework** [comment]
Tinyint is not boolean in SQL.
You can cast int type to bool type in C++ lang.
