### ISSUE TITLE
QDataStream friend functions don't let build models.

### ISSUE THREAD

**Issue by officefish** [treefrogframework/treefrog-framework#332]
Sorry for broken encodings, it is just regular linker output. So jom can not build my model because of QDataStream friend functions even tsawn generate them:

QT Output:
_user_indexView.obj:-1: ошибка: LNK2019: ббл«Є  ­  ­Ґа §аҐиҐ­­л© ў­Ґи­Ё© бЁ¬ў®« "class QDataStream & __cdecl operator<<(class QDataStream &,class User const &)" (??6@YAAEAVQDataStream@@AEAV0@AEBVUser@@@Z) ў дг­ЄжЁЁ "class QDataStream & __cdecl QtPrivate::writeSequentialContainer<class QList<class User> >(class QDataStream &,class QList<class User> const &)" (??$writeSequentialContainer@V?$QList@VUser@@@@@QtPrivate@@YAAEAVQDataStream@@AEAV1@AEBV?$QList@VUser@@@@@Z).
user_showView.obj:-1: ошибка: LNK2001: ­Ґа §аҐиҐ­­л© ў­Ґи­Ё© бЁ¬ў®« "class QDataStream & __cdecl operator<<(class QDataStream &,class User const &)" (??6@YAAEAVQDataStream@@AEAV0@AEBVUser@@@Z).
user_indexView.obj:-1: ошибка: LNK2019: ббл«Є  ­  ­Ґа §аҐиҐ­­л© ў­Ґи­Ё© бЁ¬ў®« "class QDataStream & __cdecl operator>>(class QDataStream &,class User &)" (??5@YAAEAVQDataStream@@AEAV0@AEAVUser@@@Z) ў дг­ЄжЁЁ "class QDataStream & __cdecl QtPrivate::readArrayBasedContainer<class QList<class User> >(class QDataStream &,class QList<class User> &)" (??$readArrayBasedContainer@V?$QList@VUser@@@@@QtPrivate@@YAAEAVQDataStream@@AEAV1@AEAV?$QList@VUser@@@@@Z).
user_showView.obj:-1: ошибка: LNK2001: ­Ґа §аҐиҐ­­л© ў­Ґи­Ё© бЁ¬ў®« "class QDataStream & __cdecl operator>>(class QDataStream &,class User &)" (??5@YAAEAVQDataStream@@AEAV0@AEAVUser@@@Z)._

user.h
```
#pragma once
#include <QStringList>
#include <QDateTime>
#include <QVariant>
#include <QSharedDataPointer>
#include <TGlobal>
#include <TAbstractUser>
#include <TAbstractModel>

class TModelObject;
class UserObject;
class QJsonArray;


class T_MODEL_EXPORT User : public TAbstractUser, public TAbstractModel {
public:
    User();
    User(const User &other);
    User(const UserObject &object);
    ~User();

    int id() const;
    QString name() const;
    void setName(const QString &name);
    QString sername() const;
    void setSername(const QString &sername);
    QString nickname() const;
    void setNickname(const QString &nickname);
    QString password() const;
    void setPassword(const QString &password);
    QString identityKey() const { return nickname(); }
    User &operator=(const User &other);

    bool create() { return TAbstractModel::create(); }
    bool update() { return TAbstractModel::update(); }
    bool save()   { return TAbstractModel::save(); }
    bool remove() { return TAbstractModel::remove(); }

    static User authenticate(const QString &username, const QString &password);
    static User create(const QString &name, const QString &sername, const QString &nickname, const QString &password);
    static User create(const QVariantMap &values);
    static User get(int id);
    static int count();
    static QList<User> getAll();
    static QJsonArray getAllJson(const QStringList &properties = QStringList());

private:
    QSharedDataPointer<UserObject> d;

    TModelObject *modelData();
    const TModelObject *modelData() const;
    friend QDataStream &operator<<(QDataStream &ds, const User &model);
    friend QDataStream &operator>>(QDataStream &ds, User &model);
};

Q_DECLARE_METATYPE(User)
Q_DECLARE_METATYPE(QList<User>)
```

user.cpp
```
//...
QDataStream &operator<<(QDataStream &ds, const User &model)
{
    auto varmap = model.toVariantMap();
    ds << varmap;
    return ds;
}

QDataStream &operator>>(QDataStream &ds, User &model)
{
    QVariantMap varmap;
    ds >> varmap;
    model.setProperties(varmap);
    return ds;
}
```

**Comment by treefrogframework** [comment]
This issue cannot be reproduced in version 2.1.
