### ISSUE TITLE
Feature request: support logging duration of each request or query (%T/%D in apache) 

### ISSUE THREAD

**Issue by jimis** [treefrogframework/treefrog-framework#337]
Trying to do performance optimisation, it is important to know how long each request and each SQL query took to complete. 

This ticket is about implementing `%T/%D` for `access.log` and `query.log` similar to [what Apache httpd has](https://httpd.apache.org/docs/2.4/mod/mod_log_config.html#logformat):

| symbol | meaning |
| --- | --- |
| %D | The time taken to serve the request, in microseconds. |
| %T | The time taken to serve the request, in seconds. |

In TreeFrog `%T` [already means Thread ID](https://www.treefrogframework.org/en/user-guide/helper-reference/logging.html), but even adding just `%D` would be helpful.

**Comment by treefrogframework** [comment]
@jimis 
The elapsed processing time logging in query log and access log was implemented, using "%e" parameter in the format string.
Commited in https://github.com/treefrogframework/treefrog-framework/pull/340 .

For example, can add the following settings into application.ini

```
# Specify the layout of SQL query log.
#  %d : date-time
#  %p : priority (lowercase)
#  %P : priority (uppercase)
#  %t : thread ID (dec)
#  %T : thread ID (hex)
#  %i : PID (dec)
#  %I : PID (hex)
#  %e : elapsed processing time in milliseconds
#  %m : log message
#  %n : newline code
SqlQueryLog.Layout="%d [%t] (%e) %m%n"

# Specify the date-time format of SQL query log, see also QDateTime
# class reference.
SqlQueryLog.DateTimeFormat="yyyy-MM-dd hh:mm:ss"
```

**Comment by jimis** [comment]
Thanks for the feature, very useful! FYI I had a look in the patch https://github.com/treefrogframework/treefrog-framework/pull/340 and mentioned couple of things I found.
