### ISSUE TITLE
Is it possible to use CopperSpice in place of Qt?

### ISSUE THREAD

**Issue by 3oheicrw** [treefrogframework/treefrog-framework#341]
Here is CopperSpice:

https://www.copperspice.com/

**Comment by treefrogframework** [comment]
I don't know much about CopperSpice.
You could try it.

**Comment by gi9obru0etuPlc6wozls** [comment]
Having worked with TreeFrog for years now and having modified it extensively, I can say that it would be a monumental task that would fall just short of writing a framework from scratch.

But, I am interested in the motivation of such an endeavor since Qt5/TreeFrog are so good as it is.

**Comment by 3oheicrw** [comment]
> Having worked with TreeFrog for years now and having modified it extensively, I can say that it would be a monumental task that would fall just short of writing a framework from scratch.
> 
> But, I am interested in the motivation of such an endeavor since Qt5/TreeFrog are so good as it is.

CopperSpice uses macros. Instead of Q_OBJECT you will have to write CS_OBJECT(classname). Other than that the MetaObject Model is almost the same. This is something similar to CopperSpice's macros but for Qt itself:

https://github.com/woboq/verdigris

I don't think it will as large as rewriting the framework from scratch. Hope you will have a lot of fun during the endeavor.
