### ISSUE TITLE
How do I access static files 

### ISSUE THREAD

**Issue by luoshengke** [treefrogframework/treefrog-framework#349]
I am a newbie and I plan to migrate the Web service QtWebApp to Cutelyst. I use the Web UI framework Vue to package the build and generate the Dist folder and index.html. How to run index.html with treefrog; (The previous Web service I used was the StaticFileController class in the QtWebApp framework.)

**Comment by treefrogframework** [comment]
Please ask [Cutelyst](https://github.com/cutelyst/cutelyst) the question.
