### ISSUE TITLE
Can it be compiled to 32 bits

### ISSUE THREAD

**Issue by luoshengke** [treefrogframework/treefrog-framework#351]
(1)if only to 64 bits, can it be used by a 32 bit exe,     
(2) How do I avoid compiling  "MongoDB"

**Comment by treefrogframework** [comment]
(1) No. You can compile it on msvc2017-32bit, see [here](https://ci.appveyor.com/project/treefrogframework/treefrog-framework/builds/43688861/job/pn40quqcfs310ptq).

(2) On windows, cannot avoid compiling "MongoDB".
