### ISSUE TITLE
[Question] - WebAPI

### ISSUE THREAD

**Issue by rmszc81** [treefrogframework/treefrog-framework#352]
Hello,
first, thank you for providing us such great framework, it's really awesome.

Second, I have a question:
- How can we create a Web API with treeframework? Controllers without views?
Thank you,

@rmszc81

**Comment by treefrogframework** [comment]
@rmszc81
It may be my cheap English, I made a page about Web API.
See the page - https://www.treefrogframework.org/en/user-guide/controller/webapi.html

**Comment by rmszc81** [comment]
Hello,
I'm not an English native speaker too so, no worries.
I understood the page and the example very well.
Thank you very much for the clarification ^^
Regards,
@rmszc81
