### ISSUE TITLE
LZ4 build failed

### ISSUE THREAD

**Issue by Llugway** [treefrogframework/treefrog-framework#354]
Hello,

i'm trying to build the framework.

This appears during build.bat script :

-----------------------------------------------------------------------

1>------ Début de la regénération globale : Projet : liblz4, Configuration : Release x64 ------
1>lz4.c
1>lz4frame.c
1>lz4hc.c
1>xxhash.c
1>liblz4.vcxproj -> C:\Program Files (x86)\TreeFrog\treefrog-framework-2.3.1\3rdparty\lz4\build\VS2017\bin\x64_Release\liblz4_static.lib
c:\program files (x86)\treefrog\treefrog-framework-2.3.1\3rdparty\lz4\lib\lz4.c(489): warning C6385: Lecture de données non valides depuis 'v' : la taille lisible est '_Old_4`2' octets, mais '4' octets sont peut-être lus.
1>Nombre de paramètres non valide
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: La commande "xcopy /Y C:\Program Files (x86)\TreeFrog\treefrog-framework-2.3.1\3rdparty\lz4\build\VS2017\bin\x64_Release\liblz4_static.lib  C:\Program Files (x86)\TreeFrog\treefrog-framework-2.3.1\3rdparty\lz4\build\VS2017\bin\x64_Release\..\..\..
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" s'est arrêtée avec le code 4.
1>Génération du projet "liblz4.vcxproj" terminée -- ÉCHEC.
========== Regénération globale : 0 a réussi, 1 a échoué, 0 a été ignoré ==========

1>------ Début de la génération : Projet : liblz4, Configuration : Release x64 ------
1>liblz4.vcxproj -> C:\Program Files (x86)\TreeFrog\treefrog-framework-2.3.1\3rdparty\lz4\build\VS2017\bin\x64_Release\liblz4_static.lib
1>Nombre de paramètres non valide
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: La commande "xcopy /Y C:\Program Files (x86)\TreeFrog\treefrog-framework-2.3.1\3rdparty\lz4\build\VS2017\bin\x64_Release\liblz4_static.lib  C:\Program Files (x86)\TreeFrog\treefrog-framework-2.3.1\3rdparty\lz4\build\VS2017\bin\x64_Release\..\..\..
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" s'est arrêtée avec le code 4.
1>Génération du projet "liblz4.vcxproj" terminée -- ÉCHEC.
========== Génération : 0 a réussi, 1 a échoué, 0 à jour, 0 a été ignoré ==========

Build failed.
LZ4 not available.

Compilation Error!!!

-----------------------------------------------------------------------

This talk about nb of parameters not good

Ty for your help.

**Comment by treefrogframework** [comment]
See [INSTALL](https://www.treefrogframework.org/en/user-guide/install/) page.
Don't use build.bat.
