### ISSUE TITLE
Conditionally build lz4 and glog

### ISSUE THREAD

**Issue by chenrui333** [treefrogframework/treefrog-framework#370]
Right now it always compile lz4 and glog, but it [caused some build issue](https://github.com/Homebrew/homebrew-core/pull/115013), it would be good to conditionally link to the system built lz4 and glog instead of [always building them](https://github.com/treefrogframework/treefrog-framework/blob/ddc43f940de0e230264376ca5082ad7af2e99285/configure#L211-L239). Thanks!

**Comment by treefrogframework** [comment]
Added a link option for LZ4 shared library in version 2.6.1.
