### ISSUE TITLE
Can treefrog be used as rest server with auth like cppcms?

### ISSUE THREAD

**Issue by lovelypp777** [treefrogframework/treefrog-framework#386]
Can treefrog be used as rest server with auth like cppcms? Is there any example or doc ?
thanks!

**Comment by treefrogframework** [comment]
There is not much documentation. 
See here,
 https://www.treefrogframework.org/en/user-guide/controller/webapi.html
 https://www.treefrogframework.org/en/user-guide/helper-reference/authentication.html
