### ISSUE TITLE
Upgrade libpq client library

### ISSUE THREAD

**Issue by amiart** [treefrogframework/treefrog-framework#392]
The libpq.dll 9.4.5 library shipped with Treefrog doesn't support scram-sha-256 authentication.
When I try to connect to PostgreSQL 16.1 on Windows I get error:

> authentication method 10 not supported

Please upgrade libpg to at least 10.x that supports scram-sha-256.

**Comment by treefrogframework** [comment]
@amiart Upgraded libpq.
https://github.com/treefrogframework/treefrog-framework/releases/tag/v2.8.0-2

Thanks!
