### ISSUE TITLE
can not config application start action

### ISSUE THREAD

**Issue by liyingzh** [treefrogframework/treefrog-framework#43]
treefrog start with index in default, if it can be such as login by config?
I mean start with login rather than default index.

**Comment by treefrogframework** [comment]
You can edit config/routes.cfg.

See http://www.treefrogframework.org/documents/controller/url-routing

**Comment by liyingzh** [comment]
Thank you! @treefrogframework 
Our project: https://github.com/CMS-Project/CMS
