### ISSUE TITLE
tools tspawn only suport one field primary key

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#48]
If the database table have a Composite Primary, this tool only use one field.

**Comment by treefrogframework** [comment]
It's spec.
If there are any inconveniences, tell me.

**Comment by hks2002** [comment]
Some of my database table have used composite primary key. if this tools could let me use getbyprimarykey(QString pkfiled1,QString pkfield2), it will be more flex. if not, the generated model seems have no primary key, but database table indeed have.

**Comment by treefrogframework** [comment]
In case of composite primary key,  you need to create a method into the model
class as below.

Foo getByPrimaryKey(QString pkfiled1,QString pkfield2)
{
  TCriteria cri;
  cri.add(FooObject::PkField1, pkfiled1);
  cri.add(FooObject::PkField2, pkfiled2);

  TSqlORMapper<FooObject> mapper;
  return Foo(mapper.findFirst(cri));
}

**Comment by hks2002** [comment]
yes, it can be achieved by this way.
but pkindex method in sqlobj is still return only one pkindex. as below. 
int SqlObjGenerator::primaryKeyIndex() const
{
    return tableSch->primaryKeyIndex();
}

and we can't generate  this code automatic by simply use tspawn s command. （My database table have more than 500 tables, many of them are composite primary key, so i wish it could be more smart)
so, may be you still need to spend some time to change the primarykeyindex from int to List<int>
