### ISSUE TITLE
erbpaser tr() scope is not only html innertext.

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#49]
At present ,tr() scope is html outter html,too many unnessesary tag,attribute in tr() function,
see below:
responsebody += tr(" <style type=\"text/css\">\r\n    html, body{\r\n        margin:0;padding:0;border:0;width:100%;height:100%;overflow:hidden;\r\n    }\r\n   .New_Button, .Edit_Button, .Delete_Button, .Update_Button, .Cancel_Button\r\n    {\r\n        font-size:11px;color:#1B3F91;font-family:Verdana;\r\n        margin-right:5px;\r\n    }\r\n    </style>\r\n  <h1>List UtlMenu</h1>\r\n  <div class=\"mini-fit\">\r\n    <div id=\"datagrid1\" class=\"mini-datagrid\"  style=\"width:100%;height:100%;\" url=\"/utlMenu/indexJson\" pageSize=\"10\">\r\n        <div property=\"columns\">\r\n 
i feel only text which shown in webpage is better.

**Comment by treefrogframework** [comment]
Show me the original ERB file.
I will check it.

**Comment by hks2002** [comment]
<h1>Show UtlMenu</h1>
    <div id="form1" >
        <table>
            <tr>
<td><label>Menu ID</label></td>
<td><input id="menuId" name="menuId" class="mini-textbox" enabled=false /></td>
</tr>
<tr>
<td><label>Menu Name</label></td>
<td><input id="menuName" name="menuName" class="mini-textbox" enabled=false /></td>
</tr>
<tr>
<td><label>Menu Text</label></td>
<td><input id="menuText" name="menuText" class="mini-textbox" enabled=false /></td>
</tr>
<tr>
<td><label>Menu Icon</label></td>
<td><input id="menuIcon" name="menuIcon" class="mini-textbox" enabled=false /></td>
</tr>
<tr>
<td><label>Menu Tooltip</label></td>
<td><input id="menuTooltip" name="menuTooltip" class="mini-textbox" enabled=false /></td>
</tr>
<tr>
<td><label>Menu Item Desc</label></td>
<td><input id="menuItemDesc" name="menuItemDesc" class="mini-textbox" enabled=false /></td>
</tr>
<tr>
<td><label>All Users Bool</label></td>
<td><input id="allUsersBool" name="allUsersBool" class="mini-checkbox" enabled=false /></td>
</tr>
<tr>
<td><label>Id2</label></td>
<td><input id="id2" name="id2" class="mini-textbox" enabled=false /></td>
</tr>

        </table>
    </div>
    <script type="text/javascript">
        mini.parse();

        var form = new mini.Form("#form1");
        $.ajax({
                url: '/utlMenu/getJsonBy/',
                type: 'get',
                success: function (data) {
                    form.setData(data); 
                }
            });
    </script>

**Comment by treefrogframework** [comment]
"\r\n" not needed?
I will consider it.

**Comment by hks2002** [comment]
HTML tag and tag attribute not needed also. for example:
<h1>Show UtlMenu</h1><td><label>Menu ID</label></td>
to 
tr("Show UtlMenu") + tr("Menu ID")

**Comment by treefrogframework** [comment]
The trim mode was modified in version 1.11.0.
Put '.trim_mode' file in each view subdirectories, set to 2, and rebuild them.
