### ISSUE TITLE
need new function variableNameToFieldName in TAbstractModel

### ISSUE THREAD

**Issue by hks2002** [treefrogframework/treefrog-framework#53]
currently, TAbstractModel class has a function fieldNameToVariableName, the database field can convert to variablename,
but if i want to set sort field,  the TSqlORMapper class function void setSortOrder(int column, Tf::SortOrder order) only support int, not support the variablename. i can't derectly set the variablename as the sort field.
Mostly, the sort field name is generated from the web ui (table or grid) by user,  and send the sort field name by httprequest. So, i think this function is very necessary.

**Comment by hks2002** [comment]
The QSqlTableModel class provide a function int	fieldIndex(const QString & fieldName) const, but this need fieldname.

**Comment by treefrogframework** [comment]
You mean this?
01b7a32a31febdf7667b7ce1bd533eca225b793f
5d9db2220ca2cc71fa0197a9a7c9a1b226a721c8

**Comment by hks2002** [comment]
Yes, thanks a lot.

**Comment by treefrogframework** [comment]
This patches were relesed in version 1.11.0.
