### ISSUE TITLE
upsert support

### ISSUE THREAD

**Issue by arietto** [treefrogframework/treefrog-framework#54]
Hello! PosgreSQL 9.5+ supports UPSERT. Can it be used in Treefrog internally? If not, what analog can be used instead (without using raw SQL directly)?

**Comment by treefrogframework** [comment]
I think TreeFrog must support UPSERT (or such functionality) in future.
Not only PostgreSQL but also MySQL, Oracle, etc.

**Comment by treefrogframework** [comment]
Using save() function of TSqlObject class for MySQL and PostgreSQL, it would call upsert query.
