### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by ngocdo1987** [treefrogframework/treefrog-framework#55]
Hello Treefrog author

I'm very interesting in Treefrog framework, I decide to use it for my website, but I don't know how to paginate with it. Can you write a simple tutorial for pagination?

**Comment by treefrogframework** [comment]
Sorry, Japanese tutorial only.
http://www.treefrogframework.org/ja/%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88/%E3%83%98%E3%83%AB%E3%83%91%E3%83%BC%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/%E3%83%9A%E3%83%BC%E3%82%B8%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3

And, API reference here, http://treefrogframework.org/tf_doxygen/classTPaginator.html
