### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by Zitrax** [treefrogframework/treefrog-framework#58]
Is HTTPS supported or possible to use with treefrog ?

**Comment by treefrogframework** [comment]
No.
But, you can set up a reverse proxy server, Apache or nginx.
I think Web server should perform HTTPS processing.

See http://www.treefrogframework.org/documents/cooperation-with-the-reverse-proxy-server

**Comment by Zitrax** [comment]
Right, I see. Thanks.
