### ISSUE TITLE
strip error

### ISSUE THREAD

**Issue by gonboy** [treefrogframework/treefrog-framework#61]
strip C:/TreeFrog/1.12.0/bin/tfenv.bat
strip:C:/TreeFrog/1.12.0/bin/tfenv.bat: File format not recognized
Makefile.Release:4793: recipe for target 'install_script' failed
mingw32-make[1]: [install_script] Error 1 (ignored)

**Comment by treefrogframework** [comment]
What command did you execute?
What did you intsall TreeFrog by?
Qt installed?
What version?

**Comment by gonboy** [comment]
1. run configure.bat
2. cd src
3. mingw32-make 

you can see makefile.Release ::

install_script: first FORCE
	@test -d C:$(INSTALL_ROOT:@msyshack@%=%)/TreeFrog/1.12.0/bin || mkdir -p C:$(INSTALL_ROOT:@msyshack@%=%)/TreeFrog/1.12.0/bin
	-$(INSTALL_PROGRAM) D:/.../tools/TreeFrog/treefrog-framework-master/tfenv.bat C:$(INSTALL_ROOT:@msyshack@%=%)/TreeFrog/1.12.0/bin/
	**-strip C:$(INSTALL_ROOT:@msyshack@%=%)/TreeFrog/1.12.0/bin/tfenv.bat**

**Comment by treefrogframework** [comment]
> mingw32-make[1]: [install_script] Error 1 (ignored)

Ignored, no error.
