### ISSUE TITLE
Is there a API module production plan?

### ISSUE THREAD

**Issue by cncap** [treefrogframework/treefrog-framework#62]
Similar to rest, soap, This is also considered a basic module of the web framework, I would like to have such a plan?

**Comment by cncap** [comment]
Thank you very much for your dedication, Treefrog has a great help to me.

**Comment by treefrogframework** [comment]
Supported already.
Define in routes.cfg.

**Comment by cncap** [comment]
Awesome!  I'm going to try it right now.
