### ISSUE TITLE
Is there an oauth2.0 example in treefrog?

### ISSUE THREAD

**Issue by cncap** [treefrogframework/treefrog-framework#63]
Sorry to bother you again, may I ask how to integrate oauth2.0 and treefrog? Is there an example

**Comment by aoym** [comment]
No such implementation of TreeFrog.
I would be happy if someone implements it.

**Comment by treefrogframework** [comment]
No such implementation of TreeFrog.
I would be happy if someone implements it.

**Comment by danyright** [comment]
Since OAuth has been added to Qt 5.8, wouldn't it be possible to integrate these classes directly in TreeFrog ?
https://doc.qt.io/qt-5/qtnetworkauth-index.html

**Comment by treefrogframework** [comment]
The OAuth modules would not be used in our framework much, because the licenses of them are Commercial or GPLv3.

So, newly implemented in e389e491d461f999d6f992d0893845a6ebc98f42.
