### ISSUE TITLE
about set QTENV

### ISSUE THREAD

**Issue by gonboy** [treefrogframework/treefrog-framework#65]
when install treefrog*.exe file, it will search QT, and maybe to detect "qtenv2.bat"
     in order to  set QTENV="...\bin\qtenv2.bat"
    So if you install **msys2** , because it's Qt don't include qtenv2.bat. so couldn't install treefrog*.exe

**Comment by treefrogframework** [comment]
So what is issue?

**Comment by gonboy** [comment]
you can using "eg. /c/treefrog/1.12.0/bin/tspawn.exe -h"  will be ok  in msys2 bash,.
but suggest fix it
