### ISSUE TITLE
about TRedis

### ISSUE THREAD

**Issue by gonboy** [treefrogframework/treefrog-framework#66]
I found  that's in controller . eg
void register(void)
{
    **TRedis redis;**
    if(!redis.isOpen())
        return;
    if(!redis.set("123","456"))
        return;
.......
}
question:
1.    That is instantiated in the function of writing is correct?
        if need to reconnect Redis every time?

2.    If it's correct.  I test, Sometimes, it will make TRedis Server to shutdown.
       But I use Flask to test Redis, it's ok.

**Comment by treefrogframework** [comment]
Edit conf/redis.ini and conf/application.ini.

 _redis.ini:_
     HostName=localhost

_application.ini:_
    RedisSettingsFile=redis.ini

Your code is correct.
 See also, http://treefrogframework.org/tf_doxygen/classTRedis.html

**Comment by gonboy** [comment]
ok! thanks
