### ISSUE TITLE
treefrog maybe add help

### ISSUE THREAD

**Issue by gonboy** [treefrogframework/treefrog-framework#68]
I try treefrog --help, but nothing.
so I search source code:
found:
        insert("-e", EnvironmentSpecified);
        insert("-s", SocketSpecified);
        insert("-v", PrintVersion);
        insert("-h", PrintUsage);
        insert("-l", ShowRunningAppList);
        insert("-d", DaemonMode);
        insert("-w", WindowsServiceMode);
        insert("-k", SendSignal);
        insert("-r", AutoReload);

and some argv send to TWebApplication eg. -i -e and webRootAbsolutePath
maybe you can add the help command.

**Comment by treefrogframework** [comment]
Try treefrog -h

**Comment by gonboy** [comment]
ok
