### ISSUE TITLE
not support windows XP

### ISSUE THREAD

**Issue by gonboy** [treefrogframework/treefrog-framework#76]
I found that's mongo-c-driver. **not support XP**.  so TreeFrog couldn't run. 

https://github.com/mongodb/libbson    (Windows Vista, 7, 8)
\3rdparty\mongo-c-driver\src\libbson\src\bson\bson-thread-private.h
#  define bson_once(o, c)                 InitOnceExecuteOnce(o, c, NULL, NULL)

windows xp kernel32.dll didn't include InitOnceExecuteOnce function.

**Comment by treefrogframework** [comment]
WindowsXP unsupported.

**Comment by gonboy** [comment]
OK . 
A lot of office development environment is XP, 
it seems that can only use the virtual machine
