### ISSUE TITLE
Is There any background jobs examples in treefrog ?

### ISSUE THREAD

**Issue by islam-taha** [treefrogframework/treefrog-framework#79]
May i ask how to implement background jobs/processes in treefrog ? is there any example ?
thanks in advance and keep the awesome work!

**Comment by treefrogframework** [comment]
TScheduler or TApplicatonScheduler can be used to execute jobs, can access databases.

See http://treefrogframework.org/tf_doxygen/classTDatabaseContext.html

**Comment by treefrogframework** [comment]
Mistook.
See http://treefrogframework.org/tf_doxygen/classTScheduler.html
