### ISSUE TITLE
SQLite and TIMESTAMP

### ISSUE THREAD

**Issue by arietto** [treefrogframework/treefrog-framework#85]
Hello! I've used Windows, treefrog 1.12.0 and SQLiteStudio 3.1.0 in order to create tables. I've added columns created_at, updated_at with type TIMESTAMP. I know that this type is not native for SQLite. The generated object (TSqlObject descendant) contained QString type instead of QDateTime. How can it be fixed? I mean not fixing in the output code (it's a workaround). 
BTW, before using TIMESTAMP I've tried INTEGER type. After switching to TIMESTAMP and calling tspawn sqlobject orders I have the following obsolete constructor
Orders::Orders()
    : TAbstractModel(), d(new OrdersObject)
{
    d->id = 0;
    d->created_at = 0;
    d->updated_at = 0;
}
So, the model also must be regenerated. But your tutorial says
"For example, after modifying a table, run the following command to update the sqlobject class only." 
You should add conditions in the tutorial (when sqlobject regeneration is enough).

**Comment by treefrogframework** [comment]
It cannot be fixed.
Please edit the code after generated.
That command is not perfect.
