### ISSUE TITLE
Decoupling ORM subsystem

### ISSUE THREAD

**Issue by arietto** [treefrogframework/treefrog-framework#87]
I'd like to use its ORM subsystem in my Qt 5.5+ based project. Are there any hints for adapting Treefrog for using in a desktop console application (just for CRUD operations, no server)? I think that the problem is linked with TDatabaseContext.
 QSqlDatabase &Tf::currentSqlDatabase(int id)
{
    return currentDatabaseContext()->getSqlDatabase(id);
}

**Comment by treefrogframework** [comment]
It would be hard to decouple the ORM because it's combining with the framework strongly.
Unit test program is a console application.
TF_TEST_MAIN macro may be a hint.

**Comment by arietto** [comment]
Thank you for your response. What is the purpose of this code fragment in the run() method (TF_TEST_MAIN)?
`QEventLoop eventLoop; `
`while (eventLoop.processEvents()) {} `
In my sample application this loop is executed only once. Why we have to create additional event loop? As far as I know, QThread already has its own QEventLoop instance.
