### ISSUE TITLE
TargetConditionals.h' file not found

### ISSUE THREAD

**Issue by Spoon94** [treefrogframework/treefrog-framework#93]
in Qt/5.6/clang_64/mkspecs/qdevice.pri file you should add this line:
!host_build:QMAKE_MAC_SDK = macosx10.xx
note:macos10.xx is depended on the Xcode version,you can check the macosx version in this dir:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.xx.sdk.
I hope my solution will help you.

**Comment by treefrogframework** [comment]
I also encountered it.
Thanks.
