### ISSUE TITLE
QSqlDatabase: QMYSQL driver not loaded

### ISSUE THREAD

**Issue by Spoon94** [treefrogframework/treefrog-framework#94]
when I use tspawn --show-tables on my mac the error occurs with the hint:
DriverType:   QMYSQL
QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE QMYSQL QMYSQL3 QODBC QODBC3 QPSQL QPSQL7
Parameter 'DriverType' is invalid or RDB client library not available.
###### 

I have recomplie mysql driver with qt.How can I fix this issue?

**Comment by treefrogframework** [comment]
Did you install the client library for MySQL?

https://github.com/treefrogframework/treefrog-framework/blob/master/INSTALL.md

**Comment by Spoon94** [comment]
I have install the Mysql5.6.

**Comment by Spoon94** [comment]
I have install the Mysql5.6.

**Comment by Spoon94** [comment]
Thank you that i didn't put dylib in /usr/local/lib

**Comment by treefrogframework** [comment]
MUST resolve all library symbols of libqsqlmysql.dylib.

$ cd (your Qt dir)/Qt5.6.2/5.6/clang_64/plugins/sqldrivers
$ otool -vL libqsqlmysql.dylib
libqsqlmysql.dylib:
	libqsqlmysql.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/mysql55/mysql/libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	@rpath/QtSql.framework/Versions/5/QtSql (compatibility version 5.6.0, current version 5.6.2)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.6.0, current version 5.6.2)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

**Comment by Spoon94** [comment]
Thank you very much. I also have complied your treefrog project on raspberry pi debian 8 successfully. If you have time,can you send me the mechanism of the treefrog project to mail:szj94@qq.com?
