### ISSUE TITLE
Nullable columns

### ISSUE THREAD

**Issue by arietto** [treefrogframework/treefrog-framework#95]
Hello. I have the following table in PostgreSQL 9.5 DBMS
CREATE TABLE public.db_audit
(
  id integer NOT NULL DEFAULT nextval('db_audit_id_seq'::regclass),
  created_at timestamp without time zone NOT NULL,
  updated_at timestamp without time zone,
  created_by integer,
  updated_by integer,
  CONSTRAINT entities_pkey PRIMARY KEY (id)
)
When I didn't fill created_by, updated_by columns for TSqlObject descendant, I had the following insert command in the log after commit:
INSERT INTO db_audit ("created_at", "updated_at", "created_by", "updated_by") VALUES (TIMESTAMP WITH TIME ZONE '2016-10-16T18:44:11.378Z', TIMESTAMP WITH TIME ZONE '2016-10-16T18:44:11.378Z', -2147483648, -65536).
Why do I have -2147483648, -65536 values? I expected null values. What is the workaround?

**Comment by treefrogframework** [comment]
It's a primitive data type in the TSqlObject class.
You can set a value in the constructor of the model class.

**Comment by arietto** [comment]
So, do you mean that this ORM can't assign NULL values for primitive types? I see that model class assigns default values in its constructor (int column defaults to zero). Why aren't primitive types wrapped into QVariant in the TSqlObject descendants? QVariant has isNull() method. What value should I put into the integer foreign key, if the parent table has no corresponding row?

**Comment by treefrogframework** [comment]
> So, do you mean that this ORM can't assign NULL values for primitive types?

In C++ lang, yes.
